/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:59:12.454051 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package orig_1kp;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class Orig_1KP_ROLE_C extends AnB_Protocol<Orig_1KP_Steps,Orig_1KP_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray Desc = null;
	private Crypto_ByteArray Price = null;
	private Crypto_ByteArray CanCa = null;
	private SecretKey HxRC = null;
	private SecretKey HxSALTC = null;
	private Crypto_ByteArray VAR_C_MCANCAHXRC = null;
	private AnBx_Params VAR_C_R1 = null;
	private Crypto_ByteArray VAR_C_J24CR1 = null;
	private Crypto_ByteArray VAR_C_HPRICEJ14CR1CJ24CR1J34CR1CMCANCAHXRCMDESCHXSALTC = null;
	private AnBx_Params VAR_C_R5 = null;
	private Crypto_ByteArray VAR_C_J12CR5 = null;
	
	
	public Orig_1KP_ROLE_C(Orig_1KP_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         CanCa = (Crypto_ByteArray) AnB_Session.readObject(sharepath+"can_"+aliases.get("ROLE_C")+"_"+aliases.get("ROLE_a")+".ser");
		 Price = (Crypto_ByteArray) AnB_Session.readObject(sharepath+"Price.ser");
		 Desc = (Crypto_ByteArray) AnB_Session.readObject(sharepath+"Desc.ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		Orig_1KP_ROLE_C.sessions = sessions;
		
		AnB_Session ROLE_C_channel_ROLE_M_Client_Insecure = lbs.get("ROLE_C_channel_ROLE_M_Client_Insecure");
        
		init();
		
        ROLE_C_channel_ROLE_M_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_C_channel_ROLE_M_Client_Insecure, Orig_1KP_Steps.STEP_0);
					executeStep(ROLE_C_channel_ROLE_M_Client_Insecure, Orig_1KP_Steps.STEP_1);
					executeStep(ROLE_C_channel_ROLE_M_Client_Insecure, Orig_1KP_Steps.STEP_2);
					executeStep(ROLE_C_channel_ROLE_M_Client_Insecure, Orig_1KP_Steps.STEP_5);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_C_channel_ROLE_M_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, Orig_1KP_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			HxRC = s.getHmacKey();
			HxSALTC = s.getHmacKey();
			VAR_C_MCANCAHXRC = s.makeHmac(CanCa,(SecretKey) HxRC);
			s.Send(new AnBx_Params(HxSALTC,VAR_C_MCANCAHXRC));

			break;
		
		case STEP_1:
			
			VAR_C_R1 = (AnBx_Params) s.Receive();
			VAR_C_J24CR1 = (Crypto_ByteArray) VAR_C_R1.getValue(1);
			seen("1.0",VAR_C_J24CR1);
			VAR_C_HPRICEJ14CR1CJ24CR1J34CR1CMCANCAHXRCMDESCHXSALTC = s.makeDigest(new AnBx_Params(Price,(Crypto_ByteArray) VAR_C_R1.getValue(0),VAR_C_J24CR1,(Crypto_ByteArray) VAR_C_R1.getValue(2),VAR_C_MCANCAHXRC,s.makeHmac(Desc,(SecretKey) HxSALTC)));
			eqCheck("1.1",(Crypto_ByteArray) VAR_C_R1.getValue(3),VAR_C_HPRICEJ14CR1CJ24CR1J34CR1CMCANCAHXRCMDESCHXSALTC);

			break;
		
		case STEP_2:
			
			s.Send(s.encrypt(new AnBx_Params(Price,VAR_C_HPRICEJ14CR1CJ24CR1J34CR1CMCANCAHXRCMDESCHXSALTC,CanCa,HxRC),aliases.get("ROLE_a")));

			break;
		
		case STEP_5:
			
			VAR_C_R5 = (AnBx_Params) s.Receive();
			VAR_C_J12CR5 = (Crypto_ByteArray) VAR_C_R5.getValue(0);
			seen("5.0",VAR_C_J12CR5);
			eqCheck("5.1",(Crypto_ByteArray) s.verify((SignedObject) VAR_C_R5.getValue(1),aliases.get("ROLE_a")),s.makeDigest(new AnBx_Params(VAR_C_J12CR5,VAR_C_HPRICEJ14CR1CJ24CR1J34CR1CMCANCAHXRCMDESCHXSALTC)));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}