/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:59:20.5954876 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package set_rev_v2;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class SET_Rev_v2_ROLE_M extends AnB_Protocol<SET_Rev_v2_Steps,SET_Rev_v2_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray OrderDesc = null;
	private Crypto_ByteArray PurchAmt = null;
	private Crypto_ByteArray NxXID = null;
	private Crypto_ByteArray SQNx4 = null;
	private Crypto_ByteArray SQNx10 = null;
	private Crypto_SealedPair VAR_M_R0 = null;
	private Crypto_ByteArray VAR_M_DMR0INVPM = null;
	private Crypto_SealedPair VAR_M_R2 = null;
	private AnBx_Params VAR_M_DMR2INVPM = null;
	private SecretKey VAR_M_DJ46MDMR2INVPMINVHKM = null;
	private Crypto_ByteArray VAR_M_MORDERDESCDJ46MDMR2INVPMINVHKM = null;
	private Crypto_SealedPair VAR_M_R4 = null;
	private Crypto_ByteArray VAR_M_R6 = null;
	private Crypto_ByteArray VAR_M_J56MDMR2INVPM = null;
	private Crypto_SealedPair VAR_M_J66MDMR2INVPM = null;
	private Crypto_SealedPair VAR_M_R8 = null;
	private AnBx_Params VAR_M_DDMR8INVPMSA = null;
	private Crypto_ByteArray VAR_M_J310MDDMR8INVPMSA = null;
	private SecretKey VAR_M_DJ410MDDMR8INVPMSAINVHKM = null;
	
	
	public SET_Rev_v2_ROLE_M(SET_Rev_v2_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         PurchAmt = (Crypto_ByteArray) AnB_Session.readObject(sharepath+"PurchAmt.ser");
		 OrderDesc = (Crypto_ByteArray) AnB_Session.readObject(sharepath+"OrderDesc.ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		SET_Rev_v2_ROLE_M.sessions = sessions;
		
		AnB_Session ROLE_M_channel_ROLE_C_Server_Insecure = lbs.get("ROLE_M_channel_ROLE_C_Server_Insecure");
        AnB_Session ROLE_M_channel_ROLE_a_Client_Insecure = lbs.get("ROLE_M_channel_ROLE_a_Client_Insecure");
        
		init();
		
        ROLE_M_channel_ROLE_C_Server_Insecure.Open();
		ROLE_M_channel_ROLE_a_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_M_channel_ROLE_C_Server_Insecure, SET_Rev_v2_Steps.STEP_0);
					executeStep(ROLE_M_channel_ROLE_C_Server_Insecure, SET_Rev_v2_Steps.STEP_1);
					executeStep(ROLE_M_channel_ROLE_C_Server_Insecure, SET_Rev_v2_Steps.STEP_2);
					executeStep(ROLE_M_channel_ROLE_C_Server_Insecure, SET_Rev_v2_Steps.STEP_3);
					executeStep(ROLE_M_channel_ROLE_C_Server_Insecure, SET_Rev_v2_Steps.STEP_4);
					executeStep(ROLE_M_channel_ROLE_a_Client_Insecure, SET_Rev_v2_Steps.STEP_5);
					executeStep(ROLE_M_channel_ROLE_a_Client_Insecure, SET_Rev_v2_Steps.STEP_6);
					executeStep(ROLE_M_channel_ROLE_a_Client_Insecure, SET_Rev_v2_Steps.STEP_7);
					executeStep(ROLE_M_channel_ROLE_a_Client_Insecure, SET_Rev_v2_Steps.STEP_8);
					executeStep(ROLE_M_channel_ROLE_C_Server_Insecure, SET_Rev_v2_Steps.STEP_9);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_M_channel_ROLE_C_Server_Insecure.Close();
		ROLE_M_channel_ROLE_a_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, SET_Rev_v2_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			// 	C -> M, (-|-|M): NxLIDM
			VAR_M_R0 = (Crypto_SealedPair) s.Receive();
			VAR_M_DMR0INVPM = (Crypto_ByteArray) s.decrypt(VAR_M_R0);
			wffCheck("0.1",VAR_M_DMR0INVPM);

			break;
		
		case STEP_1:
			
			// 	M -> C, @(M|C|-): NxXID
			NxXID = s.getNonce();
			SQNx4 = s.getSeqNumber();
			s.Send(s.sign(new AnBx_Params(aliases.get("ROLE_C"),SQNx4,NxXID)));

			break;
		
		case STEP_2:
			
			// 	C -> M, (-|-|M): NxLIDM,NxXID,[OrderDesc:M],[pan(C,a):a]
			VAR_M_R2 = (Crypto_SealedPair) s.Receive();
			VAR_M_DMR2INVPM = (AnBx_Params) s.decrypt(VAR_M_R2);
			eqCheck("2.1",NxXID,(Crypto_ByteArray) VAR_M_DMR2INVPM.getValue(1));
			VAR_M_DJ46MDMR2INVPMINVHKM = (SecretKey) s.decrypt((Crypto_SealedPair) VAR_M_DMR2INVPM.getValue(3),Crypto_KeyStoreType.hk());
			VAR_M_MORDERDESCDJ46MDMR2INVPMINVHKM = s.makeHmac(OrderDesc,(SecretKey) VAR_M_DJ46MDMR2INVPMINVHKM);
			eqCheck("2.2",(Crypto_ByteArray) VAR_M_DMR2INVPM.getValue(2),VAR_M_MORDERDESCDJ46MDMR2INVPMINVHKM);
			eqCheck("2.3",VAR_M_DMR0INVPM,(Crypto_ByteArray) VAR_M_DMR2INVPM.getValue(0));

			break;
		
		case STEP_3:
			
			
			
			s.Send(empty);

			break;
		
		case STEP_4:
			
			// 	C -> M, (-|-|a): NxLIDM,NxXID,[OrderDesc:M],[pan(C,a):a],PurchAmt,pan(C,a)
			VAR_M_R4 = (Crypto_SealedPair) s.Receive();
			wffCheck("4.1",VAR_M_R4);
			wffCheck("4.2",VAR_M_DJ46MDMR2INVPMINVHKM);

			break;
		
		case STEP_5:
			
			// 	M -> a, ^(-|-|a): NxLIDM,NxXID,[OrderDesc:M],[pan(C,a):a],PurchAmt,pan(C,a)
			s.Send(VAR_M_R4);

			break;
		
		case STEP_6:
			
			VAR_M_R6 = (Crypto_ByteArray) s.Receive();
			eqCheck("6.1",empty,VAR_M_R6);

			break;
		
		case STEP_7:
			
			// 	M -> a, @(M|a|a): NxLIDM,NxXID,[OrderDesc:M],[pan(C,a):a],PurchAmt
			SQNx10 = s.getSeqNumber();
			VAR_M_J56MDMR2INVPM = (Crypto_ByteArray) VAR_M_DMR2INVPM.getValue(4);
			VAR_M_J66MDMR2INVPM = (Crypto_SealedPair) VAR_M_DMR2INVPM.getValue(5);
			s.Send(s.encrypt(s.sign(new AnBx_Params(aliases.get("ROLE_a"),SQNx10,VAR_M_DMR0INVPM,NxXID,VAR_M_MORDERDESCDJ46MDMR2INVPMINVHKM,s.encrypt(VAR_M_DJ46MDMR2INVPMINVHKM,s.getPublicKey(aliases.get("ROLE_M"),Crypto_KeyStoreType.hk())),VAR_M_J56MDMR2INVPM,VAR_M_J66MDMR2INVPM,PurchAmt)),aliases.get("ROLE_a")));

			break;
		
		case STEP_8:
			
			// 	a -> M, @(a|M,C|M): NxLIDM,NxXID,[OrderDesc:M],[pan(C,a):a],NxAuthCode
			VAR_M_R8 = (Crypto_SealedPair) s.Receive();
			VAR_M_DDMR8INVPMSA = (AnBx_Params) s.verify((SignedObject) s.decrypt(VAR_M_R8),aliases.get("ROLE_a"));
			seen("8.0",(Crypto_ByteArray) VAR_M_DDMR8INVPMSA.getValue(7));
			eqCheck("8.1",aliases.get("ROLE_C"),(String) VAR_M_DDMR8INVPMSA.getValue(9));
			eqCheck("8.2",aliases.get("ROLE_M"),(String) VAR_M_DDMR8INVPMSA.getValue(8));
			eqCheck("8.3",NxXID,(Crypto_ByteArray) VAR_M_DDMR8INVPMSA.getValue(1));
			VAR_M_J310MDDMR8INVPMSA = (Crypto_ByteArray) VAR_M_DDMR8INVPMSA.getValue(2);
			eqCheck("8.4",VAR_M_J310MDDMR8INVPMSA,VAR_M_MORDERDESCDJ46MDMR2INVPMINVHKM);
			VAR_M_DJ410MDDMR8INVPMSAINVHKM = (SecretKey) s.decrypt((Crypto_SealedPair) VAR_M_DDMR8INVPMSA.getValue(3),Crypto_KeyStoreType.hk());
			eqCheck("8.5",VAR_M_J310MDDMR8INVPMSA,s.makeHmac(OrderDesc,(SecretKey) VAR_M_DJ410MDDMR8INVPMSAINVHKM));
			eqCheck("8.6",VAR_M_J56MDMR2INVPM,(Crypto_ByteArray) VAR_M_DDMR8INVPMSA.getValue(4));
			eqCheck("8.7",VAR_M_DMR0INVPM,(Crypto_ByteArray) VAR_M_DDMR8INVPMSA.getValue(0));
			eqCheck("8.8",VAR_M_DJ46MDMR2INVPMINVHKM,VAR_M_DJ410MDDMR8INVPMSAINVHKM);

			break;
		
		case STEP_9:
			
			// 	M -> C, ^@(a|M,C|-): NxLIDM,NxXID,[OrderDesc:M],[pan(C,a):a],NxAuthCode
			
			s.Send((SignedObject) s.decrypt(VAR_M_R8));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}