/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:59:26.0203702 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package tmn;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class TMN_ROLE_s extends AnB_Protocol<TMN_Steps,TMN_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_SealedPair VAR_S_R0 = null;
	private Crypto_ByteArray VAR_S_DSR0INVPS = null;
	private Crypto_SealedPair VAR_S_R2 = null;
	private Crypto_ByteArray VAR_S_DSR2INVPS = null;
	
	
	public TMN_ROLE_s(TMN_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		TMN_ROLE_s.sessions = sessions;
		
		AnB_Session ROLE_s_channel_ROLE_A_Server_Insecure = lbs.get("ROLE_s_channel_ROLE_A_Server_Insecure");
        AnB_Session ROLE_s_channel_ROLE_B_Client_Insecure = lbs.get("ROLE_s_channel_ROLE_B_Client_Insecure");
        
		init();
		
        ROLE_s_channel_ROLE_A_Server_Insecure.Open();
		ROLE_s_channel_ROLE_B_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_s_channel_ROLE_A_Server_Insecure, TMN_Steps.STEP_0);
					executeStep(ROLE_s_channel_ROLE_B_Client_Insecure, TMN_Steps.STEP_1);
					executeStep(ROLE_s_channel_ROLE_B_Client_Insecure, TMN_Steps.STEP_2);
					executeStep(ROLE_s_channel_ROLE_A_Server_Insecure, TMN_Steps.STEP_3);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_s_channel_ROLE_A_Server_Insecure.Close();
		ROLE_s_channel_ROLE_B_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, TMN_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			VAR_S_R0 = (Crypto_SealedPair) s.Receive();
			VAR_S_DSR0INVPS = (Crypto_ByteArray) s.decrypt(VAR_S_R0);
			wffCheck("0.1",VAR_S_DSR0INVPS);

			break;
		
		case STEP_1:
			
			s.Send(empty);

			break;
		
		case STEP_2:
			
			VAR_S_R2 = (Crypto_SealedPair) s.Receive();
			VAR_S_DSR2INVPS = (Crypto_ByteArray) s.decrypt(VAR_S_R2);
			wffCheck("2.1",VAR_S_DSR2INVPS);

			break;
		
		case STEP_3:
			
			s.Send(s.xor(VAR_S_DSR0INVPS,VAR_S_DSR2INVPS));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}