/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:59:00.0852206 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package iso4pass;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class ISO4pass_ROLE_A extends AnB_Protocol<ISO4pass_Steps,ISO4pass_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	
	// local vars
	private SecretKey ShkAs = null;
	private Crypto_ByteArray NA = null;
	private Crypto_ByteArray TVPA = null;
	private Crypto_ByteArray Text1 = null;
	private Crypto_ByteArray Text6 = null;
	private AnBx_Params VAR_A_R1 = null;
	private AnBx_Params VAR_A_DSJ23AR1SHKAS = null;
	private SecretKey VAR_A_J24ADSJ23AR1SHKAS = null;
	private AnBx_Params VAR_A_R3 = null;
	
	
	public ISO4pass_ROLE_A(ISO4pass_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         ShkAs = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_A")+"_"+aliases.get("ROLE_s")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		ISO4pass_ROLE_A.sessions = sessions;
		
		AnB_Session ROLE_A_channel_ROLE_s_Client_Insecure = lbs.get("ROLE_A_channel_ROLE_s_Client_Insecure");
        AnB_Session ROLE_A_channel_ROLE_B_Client_Insecure = lbs.get("ROLE_A_channel_ROLE_B_Client_Insecure");
        
		init();
		
        ROLE_A_channel_ROLE_s_Client_Insecure.Open();
		ROLE_A_channel_ROLE_B_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_A_channel_ROLE_s_Client_Insecure, ISO4pass_Steps.STEP_0);
					executeStep(ROLE_A_channel_ROLE_s_Client_Insecure, ISO4pass_Steps.STEP_1);
					executeStep(ROLE_A_channel_ROLE_B_Client_Insecure, ISO4pass_Steps.STEP_2);
					executeStep(ROLE_A_channel_ROLE_B_Client_Insecure, ISO4pass_Steps.STEP_3);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_A_channel_ROLE_s_Client_Insecure.Close();
		ROLE_A_channel_ROLE_B_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, ISO4pass_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			TVPA = s.getNonce();
			Text1 = s.getNonce();
			s.Send(new AnBx_Params(TVPA,aliases.get("ROLE_B"),Text1));

			break;
		
		case STEP_1:
			
			VAR_A_R1 = (AnBx_Params) s.Receive();
			VAR_A_DSJ23AR1SHKAS = (AnBx_Params) s.decrypt((SealedObject) VAR_A_R1.getValue(1),ShkAs);
			eqCheck("1.1",aliases.get("ROLE_B"),(String) VAR_A_DSJ23AR1SHKAS.getValue(2));
			eqCheck("1.2",TVPA,(Crypto_ByteArray) VAR_A_DSJ23AR1SHKAS.getValue(0));

			break;
		
		case STEP_2:
			
			
			NA = s.getNonce();
			Text6 = s.getNonce();
			VAR_A_J24ADSJ23AR1SHKAS = (SecretKey) VAR_A_DSJ23AR1SHKAS.getValue(1);
			s.Send(new AnBx_Params(Text6,(SealedObject) VAR_A_R1.getValue(2),s.encrypt(new AnBx_Params(NA,aliases.get("ROLE_B")),VAR_A_J24ADSJ23AR1SHKAS)));

			break;
		
		case STEP_3:
			
			VAR_A_R3 = (AnBx_Params) s.Receive();
			eqCheck("3.1",aliases.get("ROLE_A"),(String) new AnBx_Params((AnBx_Params) s.decrypt((SealedObject) VAR_A_R3.getValue(1),VAR_A_J24ADSJ23AR1SHKAS)).getValue(1));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}