/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:59:00.4263536 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package iso5pass;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class ISO5pass_ROLE_s extends AnB_Protocol<ISO5pass_Steps,ISO5pass_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	
	// local vars
	private SecretKey ShkAs = null;
	private SecretKey ShkBs = null;
	private Crypto_ByteArray Text3 = null;
	private Crypto_ByteArray Text4 = null;
	private Crypto_ByteArray Text5 = null;
	private SecretKey KAB = null;
	private AnBx_Params VAR_S_R1 = null;
	
	
	public ISO5pass_ROLE_s(ISO5pass_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         ShkAs = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_A")+"_"+aliases.get("ROLE_s")+".ser");
		 ShkBs = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_B")+"_"+aliases.get("ROLE_s")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		ISO5pass_ROLE_s.sessions = sessions;
		
		AnB_Session ROLE_s_channel_ROLE_B_Server_Insecure = lbs.get("ROLE_s_channel_ROLE_B_Server_Insecure");
        
		init();
		
        ROLE_s_channel_ROLE_B_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_s_channel_ROLE_B_Server_Insecure, ISO5pass_Steps.STEP_1);
					executeStep(ROLE_s_channel_ROLE_B_Server_Insecure, ISO5pass_Steps.STEP_2);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_s_channel_ROLE_B_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, ISO5pass_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_1:
			
			VAR_S_R1 = (AnBx_Params) s.Receive();
			eqCheck("1.1",aliases.get("ROLE_A"),(String) VAR_S_R1.getValue(2));

			break;
		
		case STEP_2:
			
			KAB = s.getSymmetricKey();
			
			
			Text3 = s.getNonce();
			Text4 = s.getNonce();
			Text5 = s.getNonce();
			s.Send(new AnBx_Params(Text5,s.encrypt(new AnBx_Params((Crypto_ByteArray) VAR_S_R1.getValue(0),KAB,aliases.get("ROLE_A"),Text4),ShkBs),s.encrypt(new AnBx_Params((Crypto_ByteArray) VAR_S_R1.getValue(1),KAB,aliases.get("ROLE_B"),Text3),ShkAs)));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}