/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:59:26.6896515 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package wl92;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class WL92_ROLE_B extends AnB_Protocol<WL92_Steps,WL92_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	
	// local vars
	private Crypto_ByteArray NxNB = null;
	private Crypto_SealedPair VAR_B_R2 = null;
	private AnBx_Params VAR_B_DBR2INVPB = null;
	private Crypto_ByteArray VAR_B_J12BDBR2INVPB = null;
	private AnBx_Params VAR_B_R4 = null;
	private AnBx_Params VAR_B_DJ12BR4SS = null;
	private AnBx_Params VAR_B_DDJ22BR4INVPBSS = null;
	private SealedObject VAR_B_R6 = null;
	
	
	public WL92_ROLE_B(WL92_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		WL92_ROLE_B.sessions = sessions;
		
		AnB_Session ROLE_B_channel_ROLE_A_Server_Insecure = lbs.get("ROLE_B_channel_ROLE_A_Server_Insecure");
        AnB_Session ROLE_B_channel_ROLE_s_Client_Insecure = lbs.get("ROLE_B_channel_ROLE_s_Client_Insecure");
        
		init();
		
        ROLE_B_channel_ROLE_A_Server_Insecure.Open();
		ROLE_B_channel_ROLE_s_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, WL92_Steps.STEP_2);
					executeStep(ROLE_B_channel_ROLE_s_Client_Insecure, WL92_Steps.STEP_3);
					executeStep(ROLE_B_channel_ROLE_s_Client_Insecure, WL92_Steps.STEP_4);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, WL92_Steps.STEP_5);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, WL92_Steps.STEP_6);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_B_channel_ROLE_A_Server_Insecure.Close();
		ROLE_B_channel_ROLE_s_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, WL92_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_2:
			
			VAR_B_R2 = (Crypto_SealedPair) s.Receive();
			VAR_B_DBR2INVPB = (AnBx_Params) s.decrypt(VAR_B_R2);
			eqCheck("2.1",aliases.get("ROLE_A"),(String) VAR_B_DBR2INVPB.getValue(1));

			break;
		
		case STEP_3:
			
			VAR_B_J12BDBR2INVPB = (Crypto_ByteArray) VAR_B_DBR2INVPB.getValue(0);
			s.Send(new AnBx_Params(aliases.get("ROLE_A"),aliases.get("ROLE_B"),s.encrypt(VAR_B_J12BDBR2INVPB,aliases.get("ROLE_s"))));

			break;
		
		case STEP_4:
			
			VAR_B_R4 = (AnBx_Params) s.Receive();
			VAR_B_DJ12BR4SS = (AnBx_Params) s.verify((SignedObject) VAR_B_R4.getValue(0),aliases.get("ROLE_s"));
			eqCheck("4.1",aliases.get("ROLE_A"),(String) VAR_B_DJ12BR4SS.getValue(0));
			VAR_B_DDJ22BR4INVPBSS = (AnBx_Params) s.verify((SignedObject) s.decrypt((Crypto_SealedPair) VAR_B_R4.getValue(1)),aliases.get("ROLE_s"));
			eqCheck("4.2",aliases.get("ROLE_A"),(String) VAR_B_DDJ22BR4INVPBSS.getValue(3));
			eqCheck("4.3",aliases.get("ROLE_B"),(String) VAR_B_DDJ22BR4INVPBSS.getValue(2));
			eqCheck("4.4",VAR_B_J12BDBR2INVPB,(Crypto_ByteArray) VAR_B_DDJ22BR4INVPBSS.getValue(0));

			break;
		
		case STEP_5:
			
			NxNB = s.getNonce();
			s.Send(s.encrypt(new AnBx_Params((SignedObject) s.decrypt((Crypto_SealedPair) VAR_B_R4.getValue(1)),NxNB),(PublicKey) VAR_B_DJ12BR4SS.getValue(1)));

			break;
		
		case STEP_6:
			
			VAR_B_R6 = (SealedObject) s.Receive();
			eqCheck("6.1",NxNB,(Crypto_ByteArray) s.decrypt(VAR_B_R6,(SecretKey) VAR_B_DDJ22BR4INVPBSS.getValue(1)));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}