
/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:58:53.6201645 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package forward_blind_a_digest;

import anbxj.AnBx_CommandLine_Parser;
import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.Channel_Settings;

import java.util.HashMap;
import java.util.Map;

public final class Forward_Blind_A_Digest_CommandLine_Parser extends AnBx_CommandLine_Parser<Forward_Blind_A_Digest_Roles,Forward_Blind_A_Digest_Channels> {

	public Forward_Blind_A_Digest_CommandLine_Parser(String[] args, String prot) {
		super(args, prot, prot, Forward_Blind_A_Digest_Roles.class, true);
		// AnBx_Debug.setAPPLICATION(true);
		// AnBx_Debug.setPROTOCOL(true);
		// AnBx_Debug.setSESSION(true);
		// AnBx_Debug.setLANGUAGE(true);
		// AnBx_Debug.setENCRYPTION(true);
		// AnBx_Debug.setBUSINESS_LOGIC(true);
		// AnBx_Debug.setALL(true);
    		initProtocol();
	}

	protected void initProtocol() {

		Map<String, Channel_Settings> cs = new HashMap<String, Channel_Settings>();
		Map<String, String> aliases = new HashMap<String, String>();
		Forward_Blind_A_Digest_Principal Forward_Blind_A_Digest_pr = null;
        if (role == null) terminate("no or incorrect role specified");
		AnBx_Debug.setAppname(role.toString());
		initRole(ct, role, cs, aliases, Forward_Blind_A_Digest_Roles.class, Forward_Blind_A_Digest_Channels.class);
		AnBx_Debug.out(layer, "myRole: " + role);
        AnBx_Debug.out(layer, "sessions: " + sessions);

		if (myAlias != null && keypath != null && sharepath != null) {
			Forward_Blind_A_Digest_pr = new Forward_Blind_A_Digest_Principal(myAlias, keypath, cs, aliases, crypto_config);
			switch (role) {
			case ROLE_A:
				Forward_Blind_A_Digest_pr.run(new Forward_Blind_A_Digest_ROLE_A(role, protname, sharepath),sessions);
				break;
			case ROLE_B:
				Forward_Blind_A_Digest_pr.run(new Forward_Blind_A_Digest_ROLE_B(role, protname, sharepath),sessions);
				break;
			case ROLE_C:
				Forward_Blind_A_Digest_pr.run(new Forward_Blind_A_Digest_ROLE_C(role, protname, sharepath),sessions);
				break;
			
            default:
				break;
			}
		} else terminate("Unable to initialize " + protname + " Principal");
	}
}