/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:58:50.5623941 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package carlsen;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class Carlsen_ROLE_B extends AnB_Protocol<Carlsen_Steps,Carlsen_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	
	// local vars
	private SecretKey ShkBs = null;
	private Crypto_ByteArray NxNB = null;
	private Crypto_ByteArray NxNB2 = null;
	private AnBx_Params VAR_B_R0 = null;
	private Crypto_ByteArray VAR_B_J22BR0 = null;
	private AnBx_Params VAR_B_R2 = null;
	private AnBx_Params VAR_B_DSJ12BR2SHKBS = null;
	private SecretKey VAR_B_J13BDSJ12BR2SHKBS = null;
	private SealedObject VAR_B_R4 = null;
	
	
	public Carlsen_ROLE_B(Carlsen_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         ShkBs = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_B")+"_"+aliases.get("ROLE_s")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		Carlsen_ROLE_B.sessions = sessions;
		
		AnB_Session ROLE_B_channel_ROLE_A_Server_Insecure = lbs.get("ROLE_B_channel_ROLE_A_Server_Insecure");
        AnB_Session ROLE_B_channel_ROLE_s_Client_Insecure = lbs.get("ROLE_B_channel_ROLE_s_Client_Insecure");
        
		init();
		
        ROLE_B_channel_ROLE_A_Server_Insecure.Open();
		ROLE_B_channel_ROLE_s_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, Carlsen_Steps.STEP_0);
					executeStep(ROLE_B_channel_ROLE_s_Client_Insecure, Carlsen_Steps.STEP_1);
					executeStep(ROLE_B_channel_ROLE_s_Client_Insecure, Carlsen_Steps.STEP_2);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, Carlsen_Steps.STEP_3);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, Carlsen_Steps.STEP_4);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_B_channel_ROLE_A_Server_Insecure.Close();
		ROLE_B_channel_ROLE_s_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, Carlsen_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			VAR_B_R0 = (AnBx_Params) s.Receive();
			eqCheck("0.1",aliases.get("ROLE_A"),(String) VAR_B_R0.getValue(0));

			break;
		
		case STEP_1:
			
			NxNB = s.getNonce();
			VAR_B_J22BR0 = (Crypto_ByteArray) VAR_B_R0.getValue(1);
			s.Send(new AnBx_Params(aliases.get("ROLE_A"),VAR_B_J22BR0,aliases.get("ROLE_B"),NxNB));

			break;
		
		case STEP_2:
			
			VAR_B_R2 = (AnBx_Params) s.Receive();
			wffCheck("2.1",VAR_B_J22BR0);
			VAR_B_DSJ12BR2SHKBS = (AnBx_Params) s.decrypt((SealedObject) VAR_B_R2.getValue(0),ShkBs);
			eqCheck("2.2",aliases.get("ROLE_A"),(String) VAR_B_DSJ12BR2SHKBS.getValue(2));
			eqCheck("2.3",NxNB,(Crypto_ByteArray) VAR_B_DSJ12BR2SHKBS.getValue(1));

			break;
		
		case STEP_3:
			
			NxNB2 = s.getNonce();
			VAR_B_J13BDSJ12BR2SHKBS = (SecretKey) VAR_B_DSJ12BR2SHKBS.getValue(0);
			s.Send(new AnBx_Params((SealedObject) VAR_B_R2.getValue(1),s.encrypt(VAR_B_J22BR0,VAR_B_J13BDSJ12BR2SHKBS),NxNB2));

			break;
		
		case STEP_4:
			
			VAR_B_R4 = (SealedObject) s.Receive();
			eqCheck("4.1",NxNB2,(Crypto_ByteArray) s.decrypt(VAR_B_R4,VAR_B_J13BDSJ12BR2SHKBS));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}