/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:58:50.5623941 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package carlsen;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class Carlsen_ROLE_A extends AnB_Protocol<Carlsen_Steps,Carlsen_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	
	// local vars
	private SecretKey ShkAs = null;
	private Crypto_ByteArray NxNA = null;
	private AnBx_Params VAR_A_R3 = null;
	private AnBx_Params VAR_A_DSJ13AR3SHKAS = null;
	private SecretKey VAR_A_J33ADSJ13AR3SHKAS = null;
	
	
	public Carlsen_ROLE_A(Carlsen_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         ShkAs = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_A")+"_"+aliases.get("ROLE_s")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		Carlsen_ROLE_A.sessions = sessions;
		
		AnB_Session ROLE_A_channel_ROLE_B_Client_Insecure = lbs.get("ROLE_A_channel_ROLE_B_Client_Insecure");
        
		init();
		
        ROLE_A_channel_ROLE_B_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_A_channel_ROLE_B_Client_Insecure, Carlsen_Steps.STEP_0);
					executeStep(ROLE_A_channel_ROLE_B_Client_Insecure, Carlsen_Steps.STEP_3);
					executeStep(ROLE_A_channel_ROLE_B_Client_Insecure, Carlsen_Steps.STEP_4);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_A_channel_ROLE_B_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, Carlsen_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			NxNA = s.getNonce();
			s.Send(new AnBx_Params(aliases.get("ROLE_A"),NxNA));

			break;
		
		case STEP_3:
			
			VAR_A_R3 = (AnBx_Params) s.Receive();
			VAR_A_DSJ13AR3SHKAS = (AnBx_Params) s.decrypt((SealedObject) VAR_A_R3.getValue(0),ShkAs);
			eqCheck("3.1",aliases.get("ROLE_B"),(String) VAR_A_DSJ13AR3SHKAS.getValue(1));
			eqCheck("3.2",NxNA,(Crypto_ByteArray) VAR_A_DSJ13AR3SHKAS.getValue(0));
			VAR_A_J33ADSJ13AR3SHKAS = (SecretKey) VAR_A_DSJ13AR3SHKAS.getValue(2);
			eqCheck("3.3",NxNA,(Crypto_ByteArray) s.decrypt((SealedObject) VAR_A_R3.getValue(1),VAR_A_J33ADSJ13AR3SHKAS));

			break;
		
		case STEP_4:
			
			s.Send(s.encrypt((Crypto_ByteArray) VAR_A_R3.getValue(2),VAR_A_J33ADSJ13AR3SHKAS));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}