/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-07-14 18:42:32.151879 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package andrewsecurerpc_replay;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class AndrewSecureRPC_replay_ROLE_A extends AnB_Protocol<AndrewSecureRPC_replay_Steps,AndrewSecureRPC_replay_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray tag = new Crypto_ByteArray("tag".getBytes());
	
	// local vars
	private SecretKey ShkAB = null;
	private Crypto_ByteArray NA = null;
	private SecretKey VAR_A_SHKAB = null;
	private SealedObject VAR_A_R3 = null;
	private AnBx_Params VAR_A_DSAR3ASHKAB = null;
	private Crypto_ByteArray VAR_A_J22ADSAR3ASHKAB = null;
	private SealedObject VAR_A_R7 = null;
	
	
	public AndrewSecureRPC_replay_ROLE_A(AndrewSecureRPC_replay_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         ShkAB = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_A")+"_"+aliases.get("ROLE_B")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		AndrewSecureRPC_replay_ROLE_A.sessions = sessions;
		
		AnB_Session ROLE_A_channel_ROLE_intr_Client_Insecure = lbs.get("ROLE_A_channel_ROLE_intr_Client_Insecure");
        
		init();
		
        ROLE_A_channel_ROLE_intr_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_A_channel_ROLE_intr_Client_Insecure, AndrewSecureRPC_replay_Steps.STEP_0);
					executeStep(ROLE_A_channel_ROLE_intr_Client_Insecure, AndrewSecureRPC_replay_Steps.STEP_3);
					executeStep(ROLE_A_channel_ROLE_intr_Client_Insecure, AndrewSecureRPC_replay_Steps.STEP_4);
					executeStep(ROLE_A_channel_ROLE_intr_Client_Insecure, AndrewSecureRPC_replay_Steps.STEP_7);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_A_channel_ROLE_intr_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, AndrewSecureRPC_replay_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			noteqCheck("0.1",aliases.get("ROLE_A"),aliases.get("ROLE_intr"));
			NA = s.getNonce();
			VAR_A_SHKAB = ShkAB;
			s.Send(new AnBx_Params(aliases.get("ROLE_A"),s.encrypt(new AnBx_Params(tag,NA),VAR_A_SHKAB)));

			break;
		
		case STEP_3:
			
			VAR_A_R3 = (SealedObject) s.Receive();
			VAR_A_DSAR3ASHKAB = (AnBx_Params) s.decrypt(VAR_A_R3,VAR_A_SHKAB);
			eqCheck("3.1",succ(s,NA),(Crypto_ByteArray) VAR_A_DSAR3ASHKAB.getValue(0));

			break;
		
		case STEP_4:
			
			VAR_A_J22ADSAR3ASHKAB = (Crypto_ByteArray) VAR_A_DSAR3ASHKAB.getValue(1);
			s.Send(s.encrypt(succ(s,VAR_A_J22ADSAR3ASHKAB),VAR_A_SHKAB));

			break;
		
		case STEP_7:
			
			VAR_A_R7 = (SealedObject) s.Receive();
			wffCheck("7.1",VAR_A_J22ADSAR3ASHKAB);
			wffCheck("7.2",(Crypto_ByteArray) s.decrypt(VAR_A_R7,VAR_A_SHKAB));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	private Crypto_ByteArray succ(AnB_Session s,Crypto_ByteArray par1) {
		return AndrewSecureRPC_replay_Functions.succ(s,par1);
	}
	
	

	
	

}