/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-08-01 08:31:26.4493337 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package andrewsecurerpc_replay;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Random;

public final class AndrewSecureRPC_replay_ROLE_intr extends AnB_Protocol<AndrewSecureRPC_replay_Steps,AndrewSecureRPC_replay_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray tag = new Crypto_ByteArray("tag".getBytes());
	
	// local vars
	private AnBx_Params VAR_INTR_R0 = null;
	private SealedObject VAR_INTR_J22INTRR0 = null;
	private SealedObject VAR_INTR_R2 = null;
	private SealedObject VAR_INTR_R4 = null;
	private SealedObject VAR_INTR_R6 = null;
	private SealedObject VAR_INTR_REPLAY_R7 = null;
	
	
	public AndrewSecureRPC_replay_ROLE_intr(AndrewSecureRPC_replay_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		AndrewSecureRPC_replay_ROLE_intr.sessions = sessions;
		
		AnB_Session ROLE_intr_channel_ROLE_A_Server_Insecure = lbs.get("ROLE_intr_channel_ROLE_A_Server_Insecure");
        AnB_Session ROLE_intr_channel_ROLE_B_Client_Insecure = lbs.get("ROLE_intr_channel_ROLE_B_Client_Insecure");
        
		init();
		
        ROLE_intr_channel_ROLE_A_Server_Insecure.Open();
		ROLE_intr_channel_ROLE_B_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_intr_channel_ROLE_A_Server_Insecure, AndrewSecureRPC_replay_Steps.STEP_0);
					executeStep(ROLE_intr_channel_ROLE_B_Client_Insecure, AndrewSecureRPC_replay_Steps.STEP_1);
					executeStep(ROLE_intr_channel_ROLE_B_Client_Insecure, AndrewSecureRPC_replay_Steps.STEP_2);
					executeStep(ROLE_intr_channel_ROLE_A_Server_Insecure, AndrewSecureRPC_replay_Steps.STEP_3);
					executeStep(ROLE_intr_channel_ROLE_A_Server_Insecure, AndrewSecureRPC_replay_Steps.STEP_4);
					executeStep(ROLE_intr_channel_ROLE_B_Client_Insecure, AndrewSecureRPC_replay_Steps.STEP_5);
					executeStep(ROLE_intr_channel_ROLE_B_Client_Insecure, AndrewSecureRPC_replay_Steps.STEP_6);
					executeStep(ROLE_intr_channel_ROLE_A_Server_Insecure, AndrewSecureRPC_replay_Steps.STEP_7);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_intr_channel_ROLE_A_Server_Insecure.Close();
		ROLE_intr_channel_ROLE_B_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, AndrewSecureRPC_replay_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			noteqCheck("0.2",aliases.get("ROLE_intr"),aliases.get("ROLE_A"));
			noteqCheck("0.4",aliases.get("ROLE_intr"),aliases.get("ROLE_B"));
			VAR_INTR_R0 = (AnBx_Params) s.Receive();
			VAR_INTR_J22INTRR0 = (SealedObject) VAR_INTR_R0.getValue(1);
			wffCheck("0.1",VAR_INTR_J22INTRR0);
			eqCheck("0.2",aliases.get("ROLE_A"),(String) VAR_INTR_R0.getValue(0));

			break;
		
		case STEP_1:
			
			s.Send(new AnBx_Params(aliases.get("ROLE_A"),VAR_INTR_J22INTRR0));

			break;
		
		case STEP_2:
			
			VAR_INTR_R2 = (SealedObject) s.Receive();
			wffCheck("2.1",VAR_INTR_R2);

			break;
		
		case STEP_3:
			
			s.Send(VAR_INTR_R2);

			break;
		
		case STEP_4:
			
			VAR_INTR_R4 = (SealedObject) s.Receive();
			wffCheck("4.1",VAR_INTR_R4);

			break;
		
		case STEP_5:
			
			s.Send(VAR_INTR_R4);

			break;
		
		case STEP_6:
			
			VAR_INTR_R6 = (SealedObject) s.Receive();
			wffCheck("6.1",VAR_INTR_R6);

			break;
		
		case STEP_7:
			
			if (VAR_INTR_REPLAY_R7 == null || !(new Random().nextInt(10) < 5)) {
				AnBx_Debug.out(layer, ">>> NO ATTACK <<<");
				VAR_INTR_REPLAY_R7 = VAR_INTR_R6;
				s.Send(VAR_INTR_R6);
			} else {
				// Simulate attack by sending previous message
				AnBx_Debug.out(layer, ">>> ATTACK <<<");
				s.Send(VAR_INTR_REPLAY_R7);
			}

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	private Crypto_ByteArray succ(AnB_Session s,Crypto_ByteArray par1) {
		return AndrewSecureRPC_replay_Functions.succ(s,par1);
	}
	
	

	
	

}