/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:59:16.7284653 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package rev_2kp;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class Rev_2KP_ROLE_C extends AnB_Protocol<Rev_2KP_Steps,Rev_2KP_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray Desc = null;
	private Crypto_ByteArray Price = null;
	private Crypto_ByteArray CcnCa = null;
	private SecretKey Hx3MDesc = null;
	private SecretKey Hx3accnCa = null;
	private Crypto_SealedPair VAR_C_EHX3ACCNCAHKA = null;
	private Crypto_ByteArray VAR_C_MCCNCAHX3ACCNCA = null;
	private Crypto_ByteArray VAR_C_MDESCHX3MDESC = null;
	private SignedObject VAR_C_R1 = null;
	private AnBx_Params VAR_C_DCR1SM = null;
	private Crypto_ByteArray VAR_C_J34CDCR1SM = null;
	private Crypto_ByteArray VAR_C_HPRICEJ34CDCR1SMCMCCNCAHX3ACCNCACMDESCHX3MDESC = null;
	private Crypto_ByteArray VAR_C_J44CDCR1SM = null;
	private SignedObject VAR_C_R7 = null;
	private AnBx_Params VAR_C_DCR7SA = null;
	private Crypto_ByteArray VAR_C_J26CDCR7SA = null;
	private Crypto_ByteArray VAR_C_J36CDCR7SA = null;
	
	
	public Rev_2KP_ROLE_C(Rev_2KP_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         CcnCa = (Crypto_ByteArray) AnB_Session.readObject(sharepath+"ccn_"+aliases.get("ROLE_C")+"_"+aliases.get("ROLE_a")+".ser");
		 Price = (Crypto_ByteArray) AnB_Session.readObject(sharepath+"Price.ser");
		 Desc = (Crypto_ByteArray) AnB_Session.readObject(sharepath+"Desc.ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		Rev_2KP_ROLE_C.sessions = sessions;
		
		AnB_Session ROLE_C_channel_ROLE_M_Client_Insecure = lbs.get("ROLE_C_channel_ROLE_M_Client_Insecure");
        
		init();
		
        ROLE_C_channel_ROLE_M_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_C_channel_ROLE_M_Client_Insecure, Rev_2KP_Steps.STEP_0);
					executeStep(ROLE_C_channel_ROLE_M_Client_Insecure, Rev_2KP_Steps.STEP_1);
					executeStep(ROLE_C_channel_ROLE_M_Client_Insecure, Rev_2KP_Steps.STEP_2);
					executeStep(ROLE_C_channel_ROLE_M_Client_Insecure, Rev_2KP_Steps.STEP_7);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_C_channel_ROLE_M_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, Rev_2KP_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			// 	C -> M, (-|-|M): [ccn(C,a):a],[Desc:M]
			Hx3MDesc = s.getHmacKey();
			Hx3accnCa = s.getHmacKey();
			VAR_C_EHX3ACCNCAHKA = s.encrypt(Hx3accnCa,s.getPublicKey(aliases.get("ROLE_a"),Crypto_KeyStoreType.hk()));
			VAR_C_MCCNCAHX3ACCNCA = s.makeHmac(CcnCa,(SecretKey) Hx3accnCa);
			VAR_C_MDESCHX3MDESC = s.makeHmac(Desc,(SecretKey) Hx3MDesc);
			s.Send(s.encrypt(new AnBx_Params(VAR_C_MCCNCAHX3ACCNCA,VAR_C_EHX3ACCNCAHKA,VAR_C_MDESCHX3MDESC,s.encrypt(Hx3MDesc,s.getPublicKey(aliases.get("ROLE_M"),Crypto_KeyStoreType.hk()))),aliases.get("ROLE_M")));

			break;
		
		case STEP_1:
			
			// 	M -> C, @(M|C|-): TID,[Price,TID,[ccn(C,a):a],[Desc:M]]
			VAR_C_R1 = (SignedObject) s.Receive();
			VAR_C_DCR1SM = (AnBx_Params) s.verify(VAR_C_R1,aliases.get("ROLE_M"));
			seen("1.0",(Crypto_ByteArray) VAR_C_DCR1SM.getValue(1));
			eqCheck("1.1",aliases.get("ROLE_C"),(String) VAR_C_DCR1SM.getValue(0));
			VAR_C_J34CDCR1SM = (Crypto_ByteArray) VAR_C_DCR1SM.getValue(2);
			VAR_C_HPRICEJ34CDCR1SMCMCCNCAHX3ACCNCACMDESCHX3MDESC = s.makeDigest(new AnBx_Params(Price,VAR_C_J34CDCR1SM,VAR_C_MCCNCAHX3ACCNCA,VAR_C_MDESCHX3MDESC));
			VAR_C_J44CDCR1SM = (Crypto_ByteArray) VAR_C_DCR1SM.getValue(3);
			eqCheck("1.2",VAR_C_J44CDCR1SM,VAR_C_HPRICEJ34CDCR1SMCMCCNCAHX3ACCNCACMDESCHX3MDESC);

			break;
		
		case STEP_2:
			
			// 	C -> M, (-|-|a): Price,TID,ccn(C,a),[ccn(C,a):a],[Price,TID,[ccn(C,a):a],[Desc:M]]
			s.Send(s.encrypt(new AnBx_Params(Price,VAR_C_J34CDCR1SM,CcnCa,VAR_C_MCCNCAHX3ACCNCA,VAR_C_EHX3ACCNCAHKA,VAR_C_HPRICEJ34CDCR1SMCMCCNCAHX3ACCNCACMDESCHX3MDESC),aliases.get("ROLE_a")));

			break;
		
		case STEP_7:
			
			// 	M -> C, ^(a|M,C|-): Auth,TID,[Price,TID,[ccn(C,a):a],[Desc:M]]
			VAR_C_R7 = (SignedObject) s.Receive();
			VAR_C_DCR7SA = (AnBx_Params) s.verify(VAR_C_R7,aliases.get("ROLE_a"));
			seen("7.0",(Crypto_ByteArray) VAR_C_DCR7SA.getValue(3));
			eqCheck("7.1",aliases.get("ROLE_C"),(String) VAR_C_DCR7SA.getValue(5));
			eqCheck("7.2",aliases.get("ROLE_M"),(String) VAR_C_DCR7SA.getValue(4));
			VAR_C_J26CDCR7SA = (Crypto_ByteArray) VAR_C_DCR7SA.getValue(1);
			eqCheck("7.3",VAR_C_J34CDCR1SM,VAR_C_J26CDCR7SA);
			VAR_C_J36CDCR7SA = (Crypto_ByteArray) VAR_C_DCR7SA.getValue(2);
			eqCheck("7.4",VAR_C_J36CDCR7SA,s.makeDigest(new AnBx_Params(Price,VAR_C_J34CDCR1SM,VAR_C_MCCNCAHX3ACCNCA,VAR_C_MDESCHX3MDESC)));
			eqCheck("7.5",VAR_C_J44CDCR1SM,VAR_C_J36CDCR7SA);

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}