/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:59:16.7284653 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package rev_2kp;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class Rev_2KP_ROLE_a extends AnB_Protocol<Rev_2KP_Steps,Rev_2KP_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray CcnCa = null;
	private Crypto_ByteArray Auth = null;
	private Crypto_ByteArray SQNx9 = null;
	private Crypto_SealedPair VAR_A_R3 = null;
	private SecretKey VAR_A_DJ56DAR3INVPAINVHKA = null;
	private Crypto_ByteArray VAR_A_J36DAR3INVPA = null;
	private Crypto_ByteArray VAR_A_J46DAR3INVPA = null;
	private Crypto_ByteArray VAR_A_MCCNCAADJ56DAR3INVPAINVHKA = null;
	private Crypto_SealedPair VAR_A_R5 = null;
	private AnBx_Params VAR_A_DDAR5INVPASM = null;
	private Crypto_ByteArray VAR_A_J16DAR3INVPA = null;
	private Crypto_ByteArray VAR_A_J26DAR3INVPA = null;
	private Crypto_ByteArray VAR_A_J66DAR3INVPA = null;
	private Crypto_ByteArray VAR_A_HAJ16DAR3INVPAAJ26DAR3INVPAAMCCNCAADJ56DAR3INVPAINVHKAJ47ADDAR5INVPASM = null;
	
	
	public Rev_2KP_ROLE_a(Rev_2KP_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         CcnCa = (Crypto_ByteArray) AnB_Session.readObject(sharepath+"ccn_"+aliases.get("ROLE_C")+"_"+aliases.get("ROLE_a")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		Rev_2KP_ROLE_a.sessions = sessions;
		
		AnB_Session ROLE_a_channel_ROLE_M_Server_Insecure = lbs.get("ROLE_a_channel_ROLE_M_Server_Insecure");
        
		init();
		
        ROLE_a_channel_ROLE_M_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_a_channel_ROLE_M_Server_Insecure, Rev_2KP_Steps.STEP_3);
					executeStep(ROLE_a_channel_ROLE_M_Server_Insecure, Rev_2KP_Steps.STEP_4);
					executeStep(ROLE_a_channel_ROLE_M_Server_Insecure, Rev_2KP_Steps.STEP_5);
					executeStep(ROLE_a_channel_ROLE_M_Server_Insecure, Rev_2KP_Steps.STEP_6);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_a_channel_ROLE_M_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, Rev_2KP_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_3:
			
			// 	M -> a, (-|-|a): Price,TID,ccn(C,a),[ccn(C,a):a],[Price,TID,[ccn(C,a):a],[Desc:M]]
			VAR_A_R3 = (Crypto_SealedPair) s.Receive();
			VAR_A_DJ56DAR3INVPAINVHKA = (SecretKey) s.decrypt((Crypto_SealedPair) new AnBx_Params((AnBx_Params) s.decrypt(VAR_A_R3)).getValue(4),Crypto_KeyStoreType.hk());
			VAR_A_J36DAR3INVPA = (Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.decrypt(VAR_A_R3)).getValue(2);
			VAR_A_J46DAR3INVPA = (Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.decrypt(VAR_A_R3)).getValue(3);
			eqCheck("3.1",VAR_A_J46DAR3INVPA,s.makeHmac(VAR_A_J36DAR3INVPA,(SecretKey) VAR_A_DJ56DAR3INVPAINVHKA));
			VAR_A_MCCNCAADJ56DAR3INVPAINVHKA = s.makeHmac(CcnCa,(SecretKey) VAR_A_DJ56DAR3INVPAINVHKA);
			eqCheck("3.2",VAR_A_J46DAR3INVPA,VAR_A_MCCNCAADJ56DAR3INVPAINVHKA);
			eqCheck("3.3",CcnCa,VAR_A_J36DAR3INVPA);

			break;
		
		case STEP_4:
			
			Auth = s.getNonce();
			
			
			
			
			s.Send(empty);

			break;
		
		case STEP_5:
			
			// 	M -> a, @(M|a|a): Price,[Desc:M],TID,[Price,TID,[ccn(C,a):a],[Desc:M]]
			VAR_A_R5 = (Crypto_SealedPair) s.Receive();
			VAR_A_DDAR5INVPASM = (AnBx_Params) s.verify((SignedObject) s.decrypt(VAR_A_R5),aliases.get("ROLE_M"));
			seen("5.0",(Crypto_ByteArray) VAR_A_DDAR5INVPASM.getValue(1));
			eqCheck("5.1",aliases.get("ROLE_a"),(String) VAR_A_DDAR5INVPASM.getValue(0));
			VAR_A_J16DAR3INVPA = (Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.decrypt(VAR_A_R3)).getValue(0);
			eqCheck("5.2",VAR_A_J16DAR3INVPA,(Crypto_ByteArray) VAR_A_DDAR5INVPASM.getValue(2));
			VAR_A_J26DAR3INVPA = (Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.decrypt(VAR_A_R3)).getValue(1);
			eqCheck("5.3",VAR_A_J26DAR3INVPA,(Crypto_ByteArray) VAR_A_DDAR5INVPASM.getValue(5));
			VAR_A_J66DAR3INVPA = (Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.decrypt(VAR_A_R3)).getValue(5);
			eqCheck("5.4",VAR_A_J66DAR3INVPA,(Crypto_ByteArray) VAR_A_DDAR5INVPASM.getValue(6));
			VAR_A_HAJ16DAR3INVPAAJ26DAR3INVPAAMCCNCAADJ56DAR3INVPAINVHKAJ47ADDAR5INVPASM = s.makeDigest(new AnBx_Params(VAR_A_J16DAR3INVPA,VAR_A_J26DAR3INVPA,VAR_A_MCCNCAADJ56DAR3INVPAINVHKA,(Crypto_ByteArray) VAR_A_DDAR5INVPASM.getValue(3)));
			eqCheck("5.5",VAR_A_J66DAR3INVPA,VAR_A_HAJ16DAR3INVPAAJ26DAR3INVPAAMCCNCAADJ56DAR3INVPAINVHKAJ47ADDAR5INVPASM);

			break;
		
		case STEP_6:
			
			// 	a -> M, @(a|M,C|M): Auth,TID,[Price,TID,[ccn(C,a):a],[Desc:M]]
			SQNx9 = s.getSeqNumber();
			s.Send(s.encrypt(s.sign(new AnBx_Params(Auth,VAR_A_J26DAR3INVPA,VAR_A_HAJ16DAR3INVPAAJ26DAR3INVPAAMCCNCAADJ56DAR3INVPAINVHKAJ47ADDAR5INVPASM,SQNx9,aliases.get("ROLE_M"),aliases.get("ROLE_C"))),aliases.get("ROLE_M")));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}