/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:59:19.5051868 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package set_orig;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class SET_Orig_ROLE_C extends AnB_Protocol<SET_Orig_Steps,SET_Orig_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray OrderDesc = null;
	private Crypto_ByteArray PurchAmt = null;
	private Crypto_ByteArray PanCa = null;
	private Crypto_ByteArray NxLIDM = null;
	private Crypto_ByteArray NxChallC = null;
	private SignedObject VAR_C_R1 = null;
	private AnBx_Params VAR_C_DCR1SM = null;
	private Crypto_ByteArray VAR_C_HORDERDESCPURCHAMT = null;
	private Crypto_ByteArray VAR_C_HNXLIDMJ24CDCR1SMHORDERDESCPURCHAMTPURCHAMTMHJ24CDCR1SMPANCAPANCA = null;
	private Crypto_ByteArray VAR_C_J24CDCR1SM = null;
	private Crypto_ByteArray VAR_C_J44CDCR1SM = null;
	private SignedObject VAR_C_R5 = null;
	private AnBx_Params VAR_C_DCR5SM = null;
	
	
	public SET_Orig_ROLE_C(SET_Orig_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         PanCa = (Crypto_ByteArray) AnB_Session.readObject(sharepath+"pan_"+aliases.get("ROLE_C")+"_"+aliases.get("ROLE_a")+".ser");
		 PurchAmt = (Crypto_ByteArray) AnB_Session.readObject(sharepath+"PurchAmt.ser");
		 OrderDesc = (Crypto_ByteArray) AnB_Session.readObject(sharepath+"OrderDesc.ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		SET_Orig_ROLE_C.sessions = sessions;
		
		AnB_Session ROLE_C_channel_ROLE_M_Client_Insecure = lbs.get("ROLE_C_channel_ROLE_M_Client_Insecure");
        
		init();
		
        ROLE_C_channel_ROLE_M_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_C_channel_ROLE_M_Client_Insecure, SET_Orig_Steps.STEP_0);
					executeStep(ROLE_C_channel_ROLE_M_Client_Insecure, SET_Orig_Steps.STEP_1);
					executeStep(ROLE_C_channel_ROLE_M_Client_Insecure, SET_Orig_Steps.STEP_2);
					executeStep(ROLE_C_channel_ROLE_M_Client_Insecure, SET_Orig_Steps.STEP_5);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_C_channel_ROLE_M_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, SET_Orig_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			
			NxLIDM = s.getNonce();
			NxChallC = s.getNonce();
			s.Send(new AnBx_Params(NxLIDM,NxChallC));

			break;
		
		case STEP_1:
			
			VAR_C_R1 = (SignedObject) s.Receive();
			VAR_C_DCR1SM = (AnBx_Params) s.verify(VAR_C_R1,aliases.get("ROLE_M"));
			eqCheck("1.1",NxChallC,(Crypto_ByteArray) VAR_C_DCR1SM.getValue(2));
			eqCheck("1.2",NxLIDM,(Crypto_ByteArray) VAR_C_DCR1SM.getValue(0));

			break;
		
		case STEP_2:
			
			
			
			VAR_C_HORDERDESCPURCHAMT = s.makeDigest(new AnBx_Params(OrderDesc,PurchAmt));
			VAR_C_HNXLIDMJ24CDCR1SMHORDERDESCPURCHAMTPURCHAMTMHJ24CDCR1SMPANCAPANCA = s.makeDigest(new AnBx_Params(NxLIDM,(Crypto_ByteArray) VAR_C_DCR1SM.getValue(1),VAR_C_HORDERDESCPURCHAMT,PurchAmt,aliases.get("ROLE_M"),s.makeDigest(new AnBx_Params((Crypto_ByteArray) VAR_C_DCR1SM.getValue(1),PanCa)),PanCa));
			VAR_C_J24CDCR1SM = (Crypto_ByteArray) VAR_C_DCR1SM.getValue(1);
			VAR_C_J44CDCR1SM = (Crypto_ByteArray) VAR_C_DCR1SM.getValue(3);
			s.Send(new AnBx_Params(s.sign(new AnBx_Params(VAR_C_HNXLIDMJ24CDCR1SMHORDERDESCPURCHAMTPURCHAMTMHJ24CDCR1SMPANCAPANCA,s.makeDigest(new AnBx_Params(NxLIDM,VAR_C_J24CDCR1SM,NxChallC,VAR_C_HORDERDESCPURCHAMT,VAR_C_J44CDCR1SM)))),s.encrypt(new AnBx_Params(NxLIDM,VAR_C_J24CDCR1SM,VAR_C_HORDERDESCPURCHAMT,PurchAmt,aliases.get("ROLE_M"),s.makeDigest(new AnBx_Params(VAR_C_J24CDCR1SM,PanCa)),s.makeDigest(new AnBx_Params(NxLIDM,VAR_C_J24CDCR1SM,NxChallC,VAR_C_HORDERDESCPURCHAMT,VAR_C_J44CDCR1SM)),PanCa),aliases.get("ROLE_a")),NxLIDM,VAR_C_J24CDCR1SM,NxChallC,VAR_C_HORDERDESCPURCHAMT,VAR_C_J44CDCR1SM,VAR_C_HNXLIDMJ24CDCR1SMHORDERDESCPURCHAMTPURCHAMTMHJ24CDCR1SMPANCAPANCA));

			break;
		
		case STEP_5:
			
			VAR_C_R5 = (SignedObject) s.Receive();
			VAR_C_DCR5SM = (AnBx_Params) s.verify(VAR_C_R5,aliases.get("ROLE_M"));
			eqCheck("5.1",aliases.get("ROLE_C"),(String) VAR_C_DCR5SM.getValue(0));
			eqCheck("5.2",NxChallC,(Crypto_ByteArray) VAR_C_DCR5SM.getValue(3));
			eqCheck("5.3",NxLIDM,(Crypto_ByteArray) VAR_C_DCR5SM.getValue(1));
			eqCheck("5.4",(Crypto_ByteArray) VAR_C_DCR5SM.getValue(2),VAR_C_J24CDCR1SM);
			eqCheck("5.5",s.makeDigest(PurchAmt),(Crypto_ByteArray) VAR_C_DCR5SM.getValue(4));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}