/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-04-22 19:28:23.0706813 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package kerberos_pkinit_intr;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnBx_CommandLine_Parser;
import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.Crypto_Config;
import anbxj.Crypto_KeyStoreSettings_Map;

public class Kerberos_PKINIT_intr_Setup extends AnBx_CommandLine_Parser<Kerberos_PKINIT_intr_Roles, Kerberos_PKINIT_intr_Channels> {

	public static void main(String[] args) {

		// AnBx_Debug.setAPPLICATION(true);
		// AnBx_Debug.setPROTOCOL(true);
		// AnBx_Debug.setSESSION(true);
		// AnBx_Debug.setLANGUAGE(true);
		// AnBx_Debug.setENCRYPTION(true);
		// AnBx_Debug.setBUSINESS_LOGIC(true);
		// AnBx_Debug.setALL(true); // true only for testing speed

		long start = System.nanoTime();

		Kerberos_PKINIT_intr_Setup p = new Kerberos_PKINIT_intr_Setup(args, Kerberos_PKINIT_intr_Setup.class.getSimpleName(), Kerberos_PKINIT_intr.class.getSimpleName(), true, false);
		p.setLayer(AnBx_Layers.APPLICATION);
		p.initProtocol();
		
		long end = System.nanoTime();
      	double durationInMs = (end - start) / 1_000_000.0;
		System.out.println(String.format("%s - Execution time was %.3f ms.", "Kerberos_PKINIT_intr_Setup", durationInMs));
	}

	public Kerberos_PKINIT_intr_Setup(String[] args, String prot, String configName, boolean vflag, boolean parseFullArgs) {
	 	super(args, prot, configName, Kerberos_PKINIT_intr_Roles.class, vflag, parseFullArgs);
	}

	@Override
	protected void initProtocol() {
		Map<String, String> aliases = new HashMap<String, String>();
		Kerberos_PKINIT_intr_Roles roleshare = getRoleShare(Kerberos_PKINIT_intr_Roles.class);
		readConfigFile(aliases, Kerberos_PKINIT_intr_Roles.class, roleshare);

		AnB_Crypto_Wrapper s;
		Crypto_KeyStoreSettings_Map kssd = new Crypto_KeyStoreSettings_Map(keypath, myAlias);
		s = new AnB_Crypto_Wrapper(kssd,new Crypto_Config(configFile));

        // create shared knowledge objects
		 createSharedObject(s.getSymmetricKey(), Arrays.asList(Kerberos_PKINIT_intr_Roles.ROLE_ath, Kerberos_PKINIT_intr_Roles.ROLE_gw), Arrays.asList(Kerberos_PKINIT_intr_Roles.ROLE_ath, Kerberos_PKINIT_intr_Roles.ROLE_gw), "shk", ".ser");
		 createSharedObject(s.getSymmetricKey(), Arrays.asList(Kerberos_PKINIT_intr_Roles.ROLE_gw, Kerberos_PKINIT_intr_Roles.ROLE_s), Arrays.asList(Kerberos_PKINIT_intr_Roles.ROLE_gw, Kerberos_PKINIT_intr_Roles.ROLE_s), "shk", ".ser");
		
        
        // create agreed knowledge objects
		
	}

	void createSharedObject(Object obj, List<Kerberos_PKINIT_intr_Roles> shroles, List<Kerberos_PKINIT_intr_Roles> parroles, String filenameprefix, String ext) {
	    // Create the aliases map outside of the loop
	    Map<String, String> aliases = new HashMap<String, String>();

	    // Populate the aliases map for each role
	    for (Kerberos_PKINIT_intr_Roles shrole : shroles) {
	        readConfigFile(aliases, Kerberos_PKINIT_intr_Roles.class, shrole); // Pass enum type role
	        // Construct the filename using the aliases map
	        
		    StringBuilder filenameBuilder = new StringBuilder(filenameprefix);
		    if (!parroles.isEmpty()) {
		    	for (Kerberos_PKINIT_intr_Roles parrole : parroles) {
		    		filenameBuilder.append("_").append(aliases.get(parrole.toString()));
		    	}	
		    }
            String filename = filenameBuilder.append(ext).toString();
	        AnB_Crypto_Wrapper.writeObject(obj, sharepath + filename);
	    }
	}

}