/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-08-27 18:30:00.2697215 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package sso_replay;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Random;

public final class SSO_replay_ROLE_idp extends AnB_Protocol<SSO_replay_Steps,SSO_replay_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_SealedPair VAR_IDP_R5 = null;
	private AnBx_Params VAR_IDP_DDIDPR5INVPIDPSC = null;
	private Crypto_ByteArray VAR_IDP_J55IDPDDIDPR5INVPIDPSC = null;
	
	
	public SSO_replay_ROLE_idp(SSO_replay_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		SSO_replay_ROLE_idp.sessions = sessions;
		
		AnB_Session ROLE_idp_channel_ROLE_I_Server_Insecure = lbs.get("ROLE_idp_channel_ROLE_I_Server_Insecure");
        
		init();
		
        ROLE_idp_channel_ROLE_I_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_idp_channel_ROLE_I_Server_Insecure, SSO_replay_Steps.STEP_5);
					executeStep(ROLE_idp_channel_ROLE_I_Server_Insecure, SSO_replay_Steps.STEP_6);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_idp_channel_ROLE_I_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, SSO_replay_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_5:
			
			VAR_IDP_R5 = (Crypto_SealedPair) s.Receive();
			VAR_IDP_DDIDPR5INVPIDPSC = (AnBx_Params) s.verify((SignedObject) s.decrypt(VAR_IDP_R5),aliases.get("ROLE_C"));
			wffCheck("5.1",(Crypto_ByteArray) VAR_IDP_DDIDPR5INVPIDPSC.getValue(3));
			VAR_IDP_J55IDPDDIDPR5INVPIDPSC = (Crypto_ByteArray) VAR_IDP_DDIDPR5INVPIDPSC.getValue(4);
			wffCheck("5.2",VAR_IDP_J55IDPDDIDPR5INVPIDPSC);
			eqCheck("5.3",aliases.get("ROLE_C"),(String) VAR_IDP_DDIDPR5INVPIDPSC.getValue(0));
			eqCheck("5.4",aliases.get("ROLE_idp"),(String) VAR_IDP_DDIDPR5INVPIDPSC.getValue(1));

			break;
		
		case STEP_6:
			
			s.Send(s.encrypt(s.sign(new AnBx_Params(s.sign(new AnBx_Params(aliases.get("ROLE_C"),aliases.get("ROLE_idp"))),VAR_IDP_J55IDPDDIDPR5INVPIDPSC)),aliases.get("ROLE_C")));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}