/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:59:29.7562481 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package woolammutual;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class WooLamMutual_ROLE_s extends AnB_Protocol<WooLamMutual_Steps,WooLamMutual_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	
	// local vars
	private SecretKey ShkAs = null;
	private SecretKey ShkBs = null;
	private SecretKey KAB = null;
	private AnBx_Params VAR_S_R3 = null;
	private AnBx_Params VAR_S_DSJ12SR3SHKAS = null;
	private AnBx_Params VAR_S_DSJ22SR3SHKBS = null;
	private Crypto_ByteArray VAR_S_J34SDSJ22SR3SHKBS = null;
	private Crypto_ByteArray VAR_S_J44SDSJ22SR3SHKBS = null;
	
	
	public WooLamMutual_ROLE_s(WooLamMutual_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         ShkAs = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_A")+"_"+aliases.get("ROLE_s")+".ser");
		 ShkBs = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_B")+"_"+aliases.get("ROLE_s")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		WooLamMutual_ROLE_s.sessions = sessions;
		
		AnB_Session ROLE_s_channel_ROLE_B_Server_Insecure = lbs.get("ROLE_s_channel_ROLE_B_Server_Insecure");
        
		init();
		
        ROLE_s_channel_ROLE_B_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_s_channel_ROLE_B_Server_Insecure, WooLamMutual_Steps.STEP_3);
					executeStep(ROLE_s_channel_ROLE_B_Server_Insecure, WooLamMutual_Steps.STEP_4);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_s_channel_ROLE_B_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, WooLamMutual_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_3:
			
			VAR_S_R3 = (AnBx_Params) s.Receive();
			VAR_S_DSJ12SR3SHKAS = (AnBx_Params) s.decrypt((SealedObject) VAR_S_R3.getValue(0),ShkAs);
			eqCheck("3.1",aliases.get("ROLE_A"),(String) VAR_S_DSJ12SR3SHKAS.getValue(0));
			VAR_S_DSJ22SR3SHKBS = (AnBx_Params) s.decrypt((SealedObject) VAR_S_R3.getValue(1),ShkBs);
			eqCheck("3.2",aliases.get("ROLE_A"),(String) VAR_S_DSJ22SR3SHKBS.getValue(0));
			eqCheck("3.3",aliases.get("ROLE_B"),(String) VAR_S_DSJ12SR3SHKAS.getValue(1));
			eqCheck("3.4",aliases.get("ROLE_B"),(String) VAR_S_DSJ22SR3SHKBS.getValue(1));
			VAR_S_J34SDSJ22SR3SHKBS = (Crypto_ByteArray) VAR_S_DSJ22SR3SHKBS.getValue(2);
			eqCheck("3.5",VAR_S_J34SDSJ22SR3SHKBS,(Crypto_ByteArray) VAR_S_DSJ12SR3SHKAS.getValue(2));
			VAR_S_J44SDSJ22SR3SHKBS = (Crypto_ByteArray) VAR_S_DSJ22SR3SHKBS.getValue(3);
			eqCheck("3.6",VAR_S_J44SDSJ22SR3SHKBS,(Crypto_ByteArray) VAR_S_DSJ12SR3SHKAS.getValue(3));

			break;
		
		case STEP_4:
			
			KAB = s.getSymmetricKey();
			
			
			s.Send(new AnBx_Params(s.encrypt(new AnBx_Params(aliases.get("ROLE_B"),VAR_S_J34SDSJ22SR3SHKBS,VAR_S_J44SDSJ22SR3SHKBS,KAB),ShkAs),s.encrypt(new AnBx_Params(aliases.get("ROLE_A"),VAR_S_J34SDSJ22SR3SHKBS,VAR_S_J44SDSJ22SR3SHKBS,KAB),ShkBs)));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}