/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-04-22 08:46:42.0006873 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package isopubkeytwopassmutualauthprotawauthb_intr;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class ISOpubKeyTwoPassMutualAuthProtAwauthB_intr_ROLE_A extends AnB_Protocol<ISOpubKeyTwoPassMutualAuthProtAwauthB_intr_Steps,ISOpubKeyTwoPassMutualAuthProtAwauthB_intr_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray tag = new Crypto_ByteArray("tag".getBytes());
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray NxNA = null;
	private Crypto_ByteArray Text1 = null;
	private SignedObject VAR_A_R1 = null;
	private AnBx_Params VAR_A_DAR1SS = null;
	private Crypto_ByteArray VAR_A_R7 = null;
	private AnBx_Params VAR_A_R11 = null;
	private AnBx_Params VAR_A_DJ12AR11SS = null;
	
	
	public ISOpubKeyTwoPassMutualAuthProtAwauthB_intr_ROLE_A(ISOpubKeyTwoPassMutualAuthProtAwauthB_intr_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		ISOpubKeyTwoPassMutualAuthProtAwauthB_intr_ROLE_A.sessions = sessions;
		
		AnB_Session ROLE_A_channel_ROLE_intr_Server_Insecure = lbs.get("ROLE_A_channel_ROLE_intr_Server_Insecure");
        
		init();
		
        ROLE_A_channel_ROLE_intr_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_A_channel_ROLE_intr_Server_Insecure, ISOpubKeyTwoPassMutualAuthProtAwauthB_intr_Steps.STEP_1);
					executeStep(ROLE_A_channel_ROLE_intr_Server_Insecure, ISOpubKeyTwoPassMutualAuthProtAwauthB_intr_Steps.STEP_2);
					executeStep(ROLE_A_channel_ROLE_intr_Server_Insecure, ISOpubKeyTwoPassMutualAuthProtAwauthB_intr_Steps.STEP_7);
					executeStep(ROLE_A_channel_ROLE_intr_Server_Insecure, ISOpubKeyTwoPassMutualAuthProtAwauthB_intr_Steps.STEP_8);
					executeStep(ROLE_A_channel_ROLE_intr_Server_Insecure, ISOpubKeyTwoPassMutualAuthProtAwauthB_intr_Steps.STEP_11);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_A_channel_ROLE_intr_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, ISOpubKeyTwoPassMutualAuthProtAwauthB_intr_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_1:
			
			VAR_A_R1 = (SignedObject) s.Receive();
			VAR_A_DAR1SS = (AnBx_Params) s.verify(VAR_A_R1,aliases.get("ROLE_s"));
			eqCheck("1.1",VAR_A_DAR1SS,new AnBx_Params(aliases.get("ROLE_A"),s.getPublicKey(aliases.get("ROLE_A"),Crypto_KeyStoreType.sk())));

			break;
		
		case STEP_2:
			
			Text1 = s.getNonce();
			
			s.Send(empty);

			break;
		
		case STEP_7:
			
			VAR_A_R7 = (Crypto_ByteArray) s.Receive();
			eqCheck("7.1",empty,VAR_A_R7);

			break;
		
		case STEP_8:
			
			NxNA = s.getNonce();
			s.Send(new AnBx_Params(VAR_A_R1,s.sign(new AnBx_Params(NxNA,aliases.get("ROLE_B"),Text1))));

			break;
		
		case STEP_11:
			
			VAR_A_R11 = (AnBx_Params) s.Receive();
			VAR_A_DJ12AR11SS = (AnBx_Params) s.verify((SignedObject) VAR_A_R11.getValue(0),aliases.get("ROLE_s"));
			eqCheck("11.1",aliases.get("ROLE_A"),(String) new AnBx_Params((AnBx_Params) s.verify((SignedObject) VAR_A_R11.getValue(1),(PublicKey) VAR_A_DJ12AR11SS.getValue(1))).getValue(1));
			eqCheck("11.2",aliases.get("ROLE_B"),(String) VAR_A_DJ12AR11SS.getValue(0));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}