/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:59:03.8718824 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package isopubkeytwopassunilateralauthprot;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class ISOpubKeyTwoPassUnilateralAuthProt_ROLE_B extends AnB_Protocol<ISOpubKeyTwoPassUnilateralAuthProt_Steps,ISOpubKeyTwoPassUnilateralAuthProt_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	
	// local vars
	private Crypto_ByteArray RB = null;
	private Crypto_ByteArray VAR_B_R2 = null;
	private AnBx_Params VAR_B_R4 = null;
	private AnBx_Params VAR_B_DJ22BR4J22DJ12BR4SS = null;
	
	
	public ISOpubKeyTwoPassUnilateralAuthProt_ROLE_B(ISOpubKeyTwoPassUnilateralAuthProt_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		ISOpubKeyTwoPassUnilateralAuthProt_ROLE_B.sessions = sessions;
		
		AnB_Session ROLE_B_channel_ROLE_A_Server_Insecure = lbs.get("ROLE_B_channel_ROLE_A_Server_Insecure");
        
		init();
		
        ROLE_B_channel_ROLE_A_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, ISOpubKeyTwoPassUnilateralAuthProt_Steps.STEP_2);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, ISOpubKeyTwoPassUnilateralAuthProt_Steps.STEP_3);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, ISOpubKeyTwoPassUnilateralAuthProt_Steps.STEP_4);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_B_channel_ROLE_A_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, ISOpubKeyTwoPassUnilateralAuthProt_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_2:
			
			VAR_B_R2 = (Crypto_ByteArray) s.Receive();
			wffCheck("2.1",VAR_B_R2);

			break;
		
		case STEP_3:
			
			RB = s.getNonce();
			s.Send(RB);

			break;
		
		case STEP_4:
			
			VAR_B_R4 = (AnBx_Params) s.Receive();
			VAR_B_DJ22BR4J22DJ12BR4SS = (AnBx_Params) s.verify((SignedObject) VAR_B_R4.getValue(1),(PublicKey) new AnBx_Params((AnBx_Params) s.verify((SignedObject) VAR_B_R4.getValue(0),aliases.get("ROLE_s"))).getValue(1));
			eqCheck("4.1",aliases.get("ROLE_B"),(String) VAR_B_DJ22BR4J22DJ12BR4SS.getValue(2));
			eqCheck("4.2",RB,(Crypto_ByteArray) VAR_B_DJ22BR4J22DJ12BR4SS.getValue(1));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}