/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-04-02 10:50:23.3821701 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package yahalom_intr;

import anbxj.Channel_Settings;
import anbxj.AnB_Principal;
import anbxj.Crypto_Config;

import java.util.Map;

class Yahalom_intr_Principal extends AnB_Principal {

	public Yahalom_intr_Principal(String myAlias, String path, Map<String, Channel_Settings> cs,
			Map<String, String> aliases, Crypto_Config config) {
		super(myAlias, path, cs, aliases, config);
	}

}