/*

 AnBx Compiler and Code Generator

 Copyright 2011-2024 Paolo Modesti
 Copyright 2018-2024 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2024.08 on 2025-07-07 11:18:51.412797 UTC

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package isosk2pmap;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class ISOSK2PMAP_ROLE_B extends AnB_Protocol<ISOSK2PMAP_Steps,ISOSK2PMAP_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	
	// local vars
	private SecretKey ShkAB = null;
	private Crypto_ByteArray NB = null;
	private Crypto_ByteArray Text3 = null;
	private SealedObject VAR_B_R0 = null;
	private SecretKey VAR_B_SHKAB = null;
	
	
	public ISOSK2PMAP_ROLE_B(ISOSK2PMAP_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         ShkAB = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_A")+"_"+aliases.get("ROLE_B")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		ISOSK2PMAP_ROLE_B.sessions = sessions;
		
		AnB_Session ROLE_B_channel_ROLE_A_Server_Insecure = lbs.get("ROLE_B_channel_ROLE_A_Server_Insecure");
        
		init();
		
        ROLE_B_channel_ROLE_A_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, ISOSK2PMAP_Steps.STEP_0);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, ISOSK2PMAP_Steps.STEP_1);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_B_channel_ROLE_A_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, ISOSK2PMAP_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			VAR_B_R0 = (SealedObject) s.Receive();
			VAR_B_SHKAB = ShkAB;
			eqCheck("0.1",aliases.get("ROLE_B"),(String) new AnBx_Params((AnBx_Params) s.decrypt(VAR_B_R0,VAR_B_SHKAB)).getValue(1));
			//SB: added to log the recovery of Text1
			wffCheck("0.2",(Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.decrypt(VAR_B_R0,VAR_B_SHKAB)).getValue(2));

			break;
		
		case STEP_1:
			
			Text3 = s.getNonce();
			
			NB = s.getNonce();
			s.Send(s.encrypt(new AnBx_Params(NB,aliases.get("ROLE_A"),Text3),VAR_B_SHKAB));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}