/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-04-24 16:42:51.214577 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package sso_intr;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class SSO_intr_ROLE_SP extends AnB_Protocol<SSO_intr_Steps,SSO_intr_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray ID = null;
	private Crypto_ByteArray Data = null;
	private AnBx_Params VAR_SP_R1 = null;
	private String VAR_SP_J13SPR1 = null;
	private Crypto_ByteArray VAR_SP_J33SPR1 = null;
	private AnBx_Params VAR_SP_R9 = null;
	private AnBx_Params VAR_SP_DJ12SPR9SIDP = null;
	
	
	public SSO_intr_ROLE_SP(SSO_intr_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		SSO_intr_ROLE_SP.sessions = sessions;
		
		AnB_Session ROLE_SP_channel_ROLE_intr_Server_Secure = lbs.get("ROLE_SP_channel_ROLE_intr_Server_Secure");
        
		init();
		
        ROLE_SP_channel_ROLE_intr_Server_Secure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_SP_channel_ROLE_intr_Server_Secure, SSO_intr_Steps.STEP_1);
					executeStep(ROLE_SP_channel_ROLE_intr_Server_Secure, SSO_intr_Steps.STEP_2);
					executeStep(ROLE_SP_channel_ROLE_intr_Server_Secure, SSO_intr_Steps.STEP_9);
					executeStep(ROLE_SP_channel_ROLE_intr_Server_Secure, SSO_intr_Steps.STEP_10);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_SP_channel_ROLE_intr_Server_Secure.Close();
		
	};

	protected void executeStep(AnB_Session s, SSO_intr_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_1:
			
			VAR_SP_R1 = (AnBx_Params) s.Receive();
			eqCheck("1.1",aliases.get("ROLE_SP"),(String) VAR_SP_R1.getValue(1));

			break;
		
		case STEP_2:
			
			Data = s.getNonce();
			
			ID = s.getNonce();
			VAR_SP_J13SPR1 = (String) VAR_SP_R1.getValue(0);
			VAR_SP_J33SPR1 = (Crypto_ByteArray) VAR_SP_R1.getValue(2);
			s.Send(new AnBx_Params(VAR_SP_J13SPR1,aliases.get("ROLE_idp"),aliases.get("ROLE_SP"),ID,VAR_SP_J33SPR1));

			break;
		
		case STEP_9:
			
			VAR_SP_R9 = (AnBx_Params) s.Receive();
			VAR_SP_DJ12SPR9SIDP = (AnBx_Params) s.verify((SignedObject) VAR_SP_R9.getValue(0),aliases.get("ROLE_idp"));
			eqCheck("9.1",aliases.get("ROLE_idp"),(String) VAR_SP_DJ12SPR9SIDP.getValue(1));
			eqCheck("9.2",VAR_SP_J13SPR1,(String) VAR_SP_DJ12SPR9SIDP.getValue(0));
			eqCheck("9.3",VAR_SP_J33SPR1,(Crypto_ByteArray) VAR_SP_R9.getValue(1));

			break;
		
		case STEP_10:
			
			s.Send(Data);

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}