/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:58:45.3393452 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package anbx_fresh_from_a_with_dh;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class AnBx_Fresh_from_A_with_DH_ROLE_B extends AnB_Protocol<AnBx_Fresh_from_A_with_DH_Steps,AnBx_Fresh_from_A_with_DH_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	
	// local vars
	private Crypto_ByteArray NB = null;
	private KeyPair YxY = null;
	private PublicKey VAR_B_R0 = null;
	private AnBx_Params VAR_B_R2 = null;
	private SignedObject VAR_B_J22BR2 = null;
	private AnBx_Params VAR_B_DSJ12BR2KASBR0YXY = null;
	
	
	public AnBx_Fresh_from_A_with_DH_ROLE_B(AnBx_Fresh_from_A_with_DH_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		AnBx_Fresh_from_A_with_DH_ROLE_B.sessions = sessions;
		
		AnB_Session ROLE_B_channel_ROLE_A_Server_Insecure = lbs.get("ROLE_B_channel_ROLE_A_Server_Insecure");
        
		init();
		
        ROLE_B_channel_ROLE_A_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, AnBx_Fresh_from_A_with_DH_Steps.STEP_0);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, AnBx_Fresh_from_A_with_DH_Steps.STEP_1);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, AnBx_Fresh_from_A_with_DH_Steps.STEP_2);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_B_channel_ROLE_A_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, AnBx_Fresh_from_A_with_DH_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			VAR_B_R0 = (PublicKey) s.Receive();
			wffCheck("0.1",VAR_B_R0);

			break;
		
		case STEP_1:
			
			NB = s.getNonce();
			YxY = s.getKeyEx_KeyPair();
			s.Send(s.encrypt(new AnBx_Params(s.getKeyEx_PublicKey(YxY),NB,aliases.get("ROLE_B")),aliases.get("ROLE_A")));

			break;
		
		case STEP_2:
			
			VAR_B_R2 = (AnBx_Params) s.Receive();
			VAR_B_J22BR2 = (SignedObject) VAR_B_R2.getValue(1);
			eqCheck("2.1",aliases.get("ROLE_B"),(String) new AnBx_Params((AnBx_Params) s.verify(VAR_B_J22BR2,aliases.get("ROLE_A"))).getValue(0));
			VAR_B_DSJ12BR2KASBR0YXY = (AnBx_Params) s.decrypt((SealedObject) VAR_B_R2.getValue(0),s.getKeyEx_SecretKey(VAR_B_R0,YxY));
			eqCheck("2.2",NB,(Crypto_ByteArray) VAR_B_DSJ12BR2KASBR0YXY.getValue(0));
			eqCheck("2.3",s.makeDigest(VAR_B_J22BR2),(Crypto_ByteArray) VAR_B_DSJ12BR2KASBR0YXY.getValue(1));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}