/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-28 10:33:51.8380216 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/
package anbx_from_a;

import anbxj.AnBx_Layers;
import anbxj.AnB_Crypto_Wrapper;

public class AnBx_From_A {

	final static AnBx_Layers layer = AnBx_Layers.APPLICATION;

	public static void main(String[] args) {

		AnB_Crypto_Wrapper.setLoggingExecTimeEnabled(false);
        long start = System.nanoTime();

		AnBx_From_A_CommandLine_Parser p = new AnBx_From_A_CommandLine_Parser(args,AnBx_From_A.class.getSimpleName());

        long end = System.nanoTime();
      	double durationInMs = (end - start) / 1_000_000.0;
		System.out.println(String.format("%s - Execution time was %.3f ms.", "AnBx_From_A [" + p.getRole() + "]", durationInMs));


	}
}