/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-07-21 16:15:16.6400194 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package isopubkeytwopassmutualauthprotcorr;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Random;

public final class ISOpubKeyTwoPassMutualAuthProtCorr_ROLE_A extends AnB_Protocol<ISOpubKeyTwoPassMutualAuthProtCorr_Steps,ISOpubKeyTwoPassMutualAuthProtCorr_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray tag = new Crypto_ByteArray("tag".getBytes());
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray NxNA = null;
	private Crypto_ByteArray Text1 = null;
	private SignedObject VAR_A_R0 = null;
	private AnBx_Params VAR_A_DAR0SS = null;
	private Crypto_ByteArray VAR_A_R3 = null;
	private AnBx_Params VAR_A_R5 = null;
	private AnBx_Params VAR_A_DJ12AR5SS = null;
	
	
	public ISOpubKeyTwoPassMutualAuthProtCorr_ROLE_A(ISOpubKeyTwoPassMutualAuthProtCorr_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		ISOpubKeyTwoPassMutualAuthProtCorr_ROLE_A.sessions = sessions;
		
		AnB_Session ROLE_A_channel_ROLE_s_Server_Insecure = lbs.get("ROLE_A_channel_ROLE_s_Server_Insecure");
        AnB_Session ROLE_A_channel_ROLE_B_Server_Insecure = lbs.get("ROLE_A_channel_ROLE_B_Server_Insecure");
        
		init();
		
        ROLE_A_channel_ROLE_s_Server_Insecure.Open();
		ROLE_A_channel_ROLE_B_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_A_channel_ROLE_s_Server_Insecure, ISOpubKeyTwoPassMutualAuthProtCorr_Steps.STEP_0);
					executeStep(ROLE_A_channel_ROLE_s_Server_Insecure, ISOpubKeyTwoPassMutualAuthProtCorr_Steps.STEP_1);
					executeStep(ROLE_A_channel_ROLE_B_Server_Insecure, ISOpubKeyTwoPassMutualAuthProtCorr_Steps.STEP_3);
					executeStep(ROLE_A_channel_ROLE_B_Server_Insecure, ISOpubKeyTwoPassMutualAuthProtCorr_Steps.STEP_4);
					executeStep(ROLE_A_channel_ROLE_B_Server_Insecure, ISOpubKeyTwoPassMutualAuthProtCorr_Steps.STEP_5);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_A_channel_ROLE_s_Server_Insecure.Close();
		ROLE_A_channel_ROLE_B_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, ISOpubKeyTwoPassMutualAuthProtCorr_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			VAR_A_R0 = (SignedObject) s.Receive();
			VAR_A_DAR0SS = (AnBx_Params) s.verify(VAR_A_R0,aliases.get("ROLE_s"));
			eqCheck("0.1",VAR_A_DAR0SS,new AnBx_Params(aliases.get("ROLE_A"),s.getPublicKey(aliases.get("ROLE_A"),Crypto_KeyStoreType.sk())));

			break;
		
		case STEP_1:
			
			Text1 = s.getNonce();
			
			s.Send(empty);

			break;
		
		case STEP_3:
			
			VAR_A_R3 = (Crypto_ByteArray) s.Receive();
			eqCheck("3.1",empty,VAR_A_R3);

			break;
		
		case STEP_4:
			
			NxNA = s.getNonce();
			s.Send(new AnBx_Params(VAR_A_R0,s.sign(new AnBx_Params(NxNA,aliases.get("ROLE_B"),Text1,tag))));

			break;
		
		case STEP_5:
			
			VAR_A_R5 = (AnBx_Params) s.Receive();
			VAR_A_DJ12AR5SS = (AnBx_Params) s.verify((SignedObject) VAR_A_R5.getValue(0),aliases.get("ROLE_s"));
			eqCheck("5.1",aliases.get("ROLE_A"),(String) new AnBx_Params((AnBx_Params) s.verify((SignedObject) VAR_A_R5.getValue(1),(PublicKey) VAR_A_DJ12AR5SS.getValue(1))).getValue(1));
			eqCheck("5.2",aliases.get("ROLE_B"),(String) VAR_A_DJ12AR5SS.getValue(0));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}