/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:58:46.7104377 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package basic_kerberos;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class Basic_Kerberos_ROLE_C extends AnB_Protocol<Basic_Kerberos_Steps,Basic_Kerberos_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray tag = new Crypto_ByteArray("tag".getBytes());
	
	// local vars
	private SecretKey ShkCath = null;
	private Crypto_ByteArray N1 = null;
	private Crypto_ByteArray N2 = null;
	private Crypto_ByteArray T3 = null;
	private AnBx_Params VAR_C_R1 = null;
	private AnBx_Params VAR_C_DSJ22CR1SHKCATH = null;
	private SecretKey VAR_C_J14CDSJ22CR1SHKCATH = null;
	private AnBx_Params VAR_C_R3 = null;
	private AnBx_Params VAR_C_DSJ22CR3CJ14CDSJ22CR1SHKCATH = null;
	private SecretKey VAR_C_J14CDSJ22CR3CJ14CDSJ22CR1SHKCATH = null;
	private AnBx_Params VAR_C_R5 = null;
	
	
	public Basic_Kerberos_ROLE_C(Basic_Kerberos_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         ShkCath = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_C")+"_"+aliases.get("ROLE_ath")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		Basic_Kerberos_ROLE_C.sessions = sessions;
		
		AnB_Session ROLE_C_channel_ROLE_ath_Client_Insecure = lbs.get("ROLE_C_channel_ROLE_ath_Client_Insecure");
        AnB_Session ROLE_C_channel_ROLE_gw_Client_Insecure = lbs.get("ROLE_C_channel_ROLE_gw_Client_Insecure");
        AnB_Session ROLE_C_channel_ROLE_s_Client_Insecure = lbs.get("ROLE_C_channel_ROLE_s_Client_Insecure");
        
		init();
		
        ROLE_C_channel_ROLE_ath_Client_Insecure.Open();
		ROLE_C_channel_ROLE_gw_Client_Insecure.Open();
		ROLE_C_channel_ROLE_s_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_C_channel_ROLE_ath_Client_Insecure, Basic_Kerberos_Steps.STEP_0);
					executeStep(ROLE_C_channel_ROLE_ath_Client_Insecure, Basic_Kerberos_Steps.STEP_1);
					executeStep(ROLE_C_channel_ROLE_gw_Client_Insecure, Basic_Kerberos_Steps.STEP_2);
					executeStep(ROLE_C_channel_ROLE_gw_Client_Insecure, Basic_Kerberos_Steps.STEP_3);
					executeStep(ROLE_C_channel_ROLE_s_Client_Insecure, Basic_Kerberos_Steps.STEP_4);
					executeStep(ROLE_C_channel_ROLE_s_Client_Insecure, Basic_Kerberos_Steps.STEP_5);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_C_channel_ROLE_ath_Client_Insecure.Close();
		ROLE_C_channel_ROLE_gw_Client_Insecure.Close();
		ROLE_C_channel_ROLE_s_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, Basic_Kerberos_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			N1 = s.getNonce();
			s.Send(new AnBx_Params(aliases.get("ROLE_C"),aliases.get("ROLE_gw"),N1));

			break;
		
		case STEP_1:
			
			VAR_C_R1 = (AnBx_Params) s.Receive();
			VAR_C_DSJ22CR1SHKCATH = (AnBx_Params) s.decrypt((SealedObject) VAR_C_R1.getValue(1),ShkCath);
			eqCheck("1.1",aliases.get("ROLE_gw"),(String) VAR_C_DSJ22CR1SHKCATH.getValue(3));
			eqCheck("1.2",N1,(Crypto_ByteArray) VAR_C_DSJ22CR1SHKCATH.getValue(1));

			break;
		
		case STEP_2:
			
			N2 = s.getNonce();
			VAR_C_J14CDSJ22CR1SHKCATH = (SecretKey) VAR_C_DSJ22CR1SHKCATH.getValue(0);
			s.Send(new AnBx_Params((SealedObject) VAR_C_R1.getValue(0),s.encrypt(new AnBx_Params(aliases.get("ROLE_C"),(Crypto_ByteArray) VAR_C_DSJ22CR1SHKCATH.getValue(2)),VAR_C_J14CDSJ22CR1SHKCATH),aliases.get("ROLE_s"),N2));

			break;
		
		case STEP_3:
			
			VAR_C_R3 = (AnBx_Params) s.Receive();
			VAR_C_DSJ22CR3CJ14CDSJ22CR1SHKCATH = (AnBx_Params) s.decrypt((SealedObject) VAR_C_R3.getValue(1),VAR_C_J14CDSJ22CR1SHKCATH);
			eqCheck("3.1",aliases.get("ROLE_s"),(String) VAR_C_DSJ22CR3CJ14CDSJ22CR1SHKCATH.getValue(3));
			eqCheck("3.2",N2,(Crypto_ByteArray) VAR_C_DSJ22CR3CJ14CDSJ22CR1SHKCATH.getValue(1));

			break;
		
		case STEP_4:
			
			T3 = s.getNonce();
			VAR_C_J14CDSJ22CR3CJ14CDSJ22CR1SHKCATH = (SecretKey) VAR_C_DSJ22CR3CJ14CDSJ22CR1SHKCATH.getValue(0);
			s.Send(new AnBx_Params((SealedObject) VAR_C_R3.getValue(0),s.encrypt(new AnBx_Params(aliases.get("ROLE_C"),T3),VAR_C_J14CDSJ22CR3CJ14CDSJ22CR1SHKCATH)));

			break;
		
		case STEP_5:
			
			VAR_C_R5 = (AnBx_Params) s.Receive();
			eqCheck("5.1",T3,(Crypto_ByteArray) s.decrypt((SealedObject) VAR_C_R5.getValue(0),VAR_C_J14CDSJ22CR3CJ14CDSJ22CR1SHKCATH));
			eqCheck("5.2",tag,(Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.decrypt((SealedObject) VAR_C_R5.getValue(1),VAR_C_J14CDSJ22CR3CJ14CDSJ22CR1SHKCATH)).getValue(0));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}