/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-04-22 16:55:25.3287314 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package isopubkeytwopassmutualauthprotbwautha_intr_attack;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_ROLE_intr extends AnB_Protocol<ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_Steps,ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private SignedObject VAR_INTR_R0 = null;
	private PublicKey VAR_INTR_J22DINTRR0SS = null;
	private Crypto_ByteArray VAR_INTR_R2 = null;
	private SignedObject VAR_INTR_R4 = null;
	private PublicKey VAR_INTR_J22DINTRR4SS = null;
	private Crypto_ByteArray VAR_INTR_R6 = null;
	private AnBx_Params VAR_INTR_R8 = null;
	private SignedObject VAR_INTR_J12INTRR8 = null;
	private AnBx_Params VAR_INTR_DINTRJ12INTRR8SS = null;
	private SignedObject VAR_INTR_J22INTRR8 = null;
	private AnBx_Params VAR_INTR_R10 = null;
	private SignedObject VAR_INTR_J12INTRR10 = null;
	private AnBx_Params VAR_INTR_DINTRJ12INTRR10SS = null;
	
	
	public ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_ROLE_intr(ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_ROLE_intr.sessions = sessions;
		
		AnB_Session ROLE_intr_channel_ROLE_s_Server_Insecure = lbs.get("ROLE_intr_channel_ROLE_s_Server_Insecure");
        AnB_Session ROLE_intr_channel_ROLE_A_Client_Insecure = lbs.get("ROLE_intr_channel_ROLE_A_Client_Insecure");
        AnB_Session ROLE_intr_channel_ROLE_B_Client_Insecure = lbs.get("ROLE_intr_channel_ROLE_B_Client_Insecure");
        
		init();
		
        ROLE_intr_channel_ROLE_s_Server_Insecure.Open();
		ROLE_intr_channel_ROLE_A_Client_Insecure.Open();
		ROLE_intr_channel_ROLE_B_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_intr_channel_ROLE_s_Server_Insecure, ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_Steps.STEP_0);
					executeStep(ROLE_intr_channel_ROLE_A_Client_Insecure, ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_Steps.STEP_1);
					executeStep(ROLE_intr_channel_ROLE_A_Client_Insecure, ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_Steps.STEP_2);
					executeStep(ROLE_intr_channel_ROLE_s_Server_Insecure, ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_Steps.STEP_3);
					executeStep(ROLE_intr_channel_ROLE_s_Server_Insecure, ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_Steps.STEP_4);
					executeStep(ROLE_intr_channel_ROLE_B_Client_Insecure, ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_Steps.STEP_5);
					executeStep(ROLE_intr_channel_ROLE_B_Client_Insecure, ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_Steps.STEP_6);
					executeStep(ROLE_intr_channel_ROLE_A_Client_Insecure, ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_Steps.STEP_7);
					executeStep(ROLE_intr_channel_ROLE_A_Client_Insecure, ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_Steps.STEP_8);
					executeStep(ROLE_intr_channel_ROLE_B_Client_Insecure, ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_Steps.STEP_9);
					executeStep(ROLE_intr_channel_ROLE_B_Client_Insecure, ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_Steps.STEP_10);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_intr_channel_ROLE_s_Server_Insecure.Close();
		ROLE_intr_channel_ROLE_A_Client_Insecure.Close();
		ROLE_intr_channel_ROLE_B_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, ISOpubKeyTwoPassMutualAuthProtBwauthA_intr_attack_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			VAR_INTR_R0 = (SignedObject) s.Receive();
			VAR_INTR_J22DINTRR0SS = (PublicKey) new AnBx_Params((AnBx_Params) s.verify(VAR_INTR_R0,aliases.get("ROLE_s"))).getValue(1);
			eqCheck("0.1",VAR_INTR_J22DINTRR0SS,s.getPublicKey((String) new AnBx_Params((AnBx_Params) s.verify(VAR_INTR_R0,aliases.get("ROLE_s"))).getValue(0),Crypto_KeyStoreType.sk()));
			eqCheck("0.2",(AnBx_Params) s.verify(VAR_INTR_R0,aliases.get("ROLE_s")),new AnBx_Params(aliases.get("ROLE_A"),s.getPublicKey(aliases.get("ROLE_A"),Crypto_KeyStoreType.sk())));

			break;
		
		case STEP_1:
			
			s.Send(VAR_INTR_R0);

			break;
		
		case STEP_2:
			
			VAR_INTR_R2 = (Crypto_ByteArray) s.Receive();
			eqCheck("2.1",empty,VAR_INTR_R2);

			break;
		
		case STEP_3:
			
			s.Send(empty);

			break;
		
		case STEP_4:
			
			VAR_INTR_R4 = (SignedObject) s.Receive();
			VAR_INTR_J22DINTRR4SS = (PublicKey) new AnBx_Params((AnBx_Params) s.verify(VAR_INTR_R4,aliases.get("ROLE_s"))).getValue(1);
			eqCheck("4.1",VAR_INTR_J22DINTRR4SS,s.getPublicKey((String) new AnBx_Params((AnBx_Params) s.verify(VAR_INTR_R4,aliases.get("ROLE_s"))).getValue(0),Crypto_KeyStoreType.sk()));
			eqCheck("4.2",(AnBx_Params) s.verify(VAR_INTR_R4,aliases.get("ROLE_s")),new AnBx_Params(aliases.get("ROLE_B"),s.getPublicKey(aliases.get("ROLE_B"),Crypto_KeyStoreType.sk())));

			break;
		
		case STEP_5:
			
			s.Send(VAR_INTR_R4);

			break;
		
		case STEP_6:
			
			VAR_INTR_R6 = (Crypto_ByteArray) s.Receive();
			eqCheck("6.1",empty,VAR_INTR_R6);

			break;
		
		case STEP_7:
			
			s.Send(empty);

			break;
		
		case STEP_8:
			
			VAR_INTR_R8 = (AnBx_Params) s.Receive();
			VAR_INTR_J12INTRR8 = (SignedObject) VAR_INTR_R8.getValue(0);
			VAR_INTR_DINTRJ12INTRR8SS = (AnBx_Params) s.verify(VAR_INTR_J12INTRR8,aliases.get("ROLE_s"));
			eqCheck("8.1",aliases.get("ROLE_A"),(String) VAR_INTR_DINTRJ12INTRR8SS.getValue(0));
			VAR_INTR_J22INTRR8 = (SignedObject) VAR_INTR_R8.getValue(1);
			eqCheck("8.2",aliases.get("ROLE_B"),(String) new AnBx_Params((AnBx_Params) s.verify(VAR_INTR_J22INTRR8,aliases.get("ROLE_A"))).getValue(1));
			eqCheck("8.3",VAR_INTR_J22DINTRR0SS,s.getPublicKey((String) VAR_INTR_DINTRJ12INTRR8SS.getValue(0),Crypto_KeyStoreType.sk()));
			eqCheck("8.4",VAR_INTR_J22DINTRR4SS,s.getPublicKey((String) new AnBx_Params((AnBx_Params) s.verify(VAR_INTR_J22INTRR8,aliases.get("ROLE_A"))).getValue(1),Crypto_KeyStoreType.sk()));
			eqCheck("8.5",(PublicKey) VAR_INTR_DINTRJ12INTRR8SS.getValue(1),VAR_INTR_J22DINTRR0SS);

			break;
		
		case STEP_9:
			
			s.Send(new AnBx_Params(VAR_INTR_R0,VAR_INTR_J22INTRR8));

			break;
		
		case STEP_10:
			
			VAR_INTR_R10 = (AnBx_Params) s.Receive();
			VAR_INTR_J12INTRR10 = (SignedObject) VAR_INTR_R10.getValue(0);
			eqCheck("10.1",aliases.get("ROLE_A"),(String) new AnBx_Params((AnBx_Params) s.verify((SignedObject) VAR_INTR_R10.getValue(1),aliases.get("ROLE_B"))).getValue(1));
			VAR_INTR_DINTRJ12INTRR10SS = (AnBx_Params) s.verify(VAR_INTR_J12INTRR10,aliases.get("ROLE_s"));
			eqCheck("10.2",aliases.get("ROLE_B"),(String) VAR_INTR_DINTRJ12INTRR10SS.getValue(0));
			eqCheck("10.3",VAR_INTR_J22DINTRR0SS,s.getPublicKey((String) new AnBx_Params((AnBx_Params) s.verify((SignedObject) VAR_INTR_R10.getValue(1),aliases.get("ROLE_B"))).getValue(1),Crypto_KeyStoreType.sk()));
			eqCheck("10.4",VAR_INTR_J22DINTRR4SS,s.getPublicKey((String) VAR_INTR_DINTRJ12INTRR10SS.getValue(0),Crypto_KeyStoreType.sk()));
			eqCheck("10.5",(PublicKey) VAR_INTR_DINTRJ12INTRR10SS.getValue(1),VAR_INTR_J22DINTRR4SS);

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}