/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:58:52.6005088 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package dh_auth;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class DH_auth_ROLE_B extends AnB_Protocol<DH_auth_Steps,DH_auth_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private KeyPair YxY = null;
	private AnBx_Params VAR_B_R0 = null;
	private SignedObject VAR_B_R2 = null;
	private AnBx_Params VAR_B_DBR2SA = null;
	private SignedObject VAR_B_R4 = null;
	private AnBx_Params VAR_B_DBR4SA = null;
	
	
	public DH_auth_ROLE_B(DH_auth_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		DH_auth_ROLE_B.sessions = sessions;
		
		AnB_Session ROLE_B_channel_ROLE_A_Server_Insecure = lbs.get("ROLE_B_channel_ROLE_A_Server_Insecure");
        
		init();
		
        ROLE_B_channel_ROLE_A_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, DH_auth_Steps.STEP_0);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, DH_auth_Steps.STEP_1);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, DH_auth_Steps.STEP_2);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, DH_auth_Steps.STEP_3);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, DH_auth_Steps.STEP_4);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_B_channel_ROLE_A_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, DH_auth_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			// 	A -> B, (-|-|-): A,B
			VAR_B_R0 = (AnBx_Params) s.Receive();
			eqCheck("0.1",VAR_B_R0,new AnBx_Params(aliases.get("ROLE_A"),aliases.get("ROLE_B")));

			break;
		
		case STEP_1:
			
			// 	B -> A, (-|-|-): exp(g,YxY)
			YxY = s.getKeyEx_KeyPair();
			s.Send(s.getKeyEx_PublicKey(YxY));

			break;
		
		case STEP_2:
			
			// 	A -> B, (A|B|-): Msg
			VAR_B_R2 = (SignedObject) s.Receive();
			VAR_B_DBR2SA = (AnBx_Params) s.verify(VAR_B_R2,aliases.get("ROLE_A"));
			eqCheck("2.1",aliases.get("ROLE_B"),(String) VAR_B_DBR2SA.getValue(0));

			break;
		
		case STEP_3:
			
			s.Send(empty);

			break;
		
		case STEP_4:
			
			// 	A -> B, (A|B|-): exp(g,XxX),{|Msg|}exp(exp(g,YxY),XxX)
			VAR_B_R4 = (SignedObject) s.Receive();
			VAR_B_DBR4SA = (AnBx_Params) s.verify(VAR_B_R4,aliases.get("ROLE_A"));
			eqCheck("4.1",aliases.get("ROLE_B"),(String) VAR_B_DBR4SA.getValue(0));
			eqCheck("4.2",(Crypto_ByteArray) VAR_B_DBR2SA.getValue(1),(Crypto_ByteArray) s.decrypt((SealedObject) VAR_B_DBR4SA.getValue(2),s.getKeyEx_SecretKey((PublicKey) VAR_B_DBR4SA.getValue(1),YxY)));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}