/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:59:26.6896515 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package wl92;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class WL92_ROLE_s extends AnB_Protocol<WL92_Steps,WL92_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	
	// local vars
	private SecretKey KxKS = null;
	private AnBx_Params VAR_S_R0 = null;
	private AnBx_Params VAR_S_R3 = null;
	private Crypto_ByteArray VAR_S_DJ33SR3INVPS = null;
	
	
	public WL92_ROLE_s(WL92_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		WL92_ROLE_s.sessions = sessions;
		
		AnB_Session ROLE_s_channel_ROLE_A_Server_Insecure = lbs.get("ROLE_s_channel_ROLE_A_Server_Insecure");
        AnB_Session ROLE_s_channel_ROLE_B_Server_Insecure = lbs.get("ROLE_s_channel_ROLE_B_Server_Insecure");
        
		init();
		
        ROLE_s_channel_ROLE_A_Server_Insecure.Open();
		ROLE_s_channel_ROLE_B_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_s_channel_ROLE_A_Server_Insecure, WL92_Steps.STEP_0);
					executeStep(ROLE_s_channel_ROLE_A_Server_Insecure, WL92_Steps.STEP_1);
					executeStep(ROLE_s_channel_ROLE_B_Server_Insecure, WL92_Steps.STEP_3);
					executeStep(ROLE_s_channel_ROLE_B_Server_Insecure, WL92_Steps.STEP_4);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_s_channel_ROLE_A_Server_Insecure.Close();
		ROLE_s_channel_ROLE_B_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, WL92_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			noteqCheck("0.2",aliases.get("ROLE_s"),aliases.get("ROLE_B"));
			VAR_S_R0 = (AnBx_Params) s.Receive();
			eqCheck("0.1",VAR_S_R0,new AnBx_Params(aliases.get("ROLE_A"),aliases.get("ROLE_B")));

			break;
		
		case STEP_1:
			
			KxKS = s.getSymmetricKey();
			
			
			s.Send(s.sign(new AnBx_Params(aliases.get("ROLE_B"),s.getPublicKey(aliases.get("ROLE_B"),Crypto_KeyStoreType.pk()))));

			break;
		
		case STEP_3:
			
			VAR_S_R3 = (AnBx_Params) s.Receive();
			VAR_S_DJ33SR3INVPS = (Crypto_ByteArray) s.decrypt((Crypto_SealedPair) VAR_S_R3.getValue(2));
			wffCheck("3.1",VAR_S_DJ33SR3INVPS);
			eqCheck("3.2",aliases.get("ROLE_A"),(String) VAR_S_R3.getValue(0));
			eqCheck("3.3",aliases.get("ROLE_B"),(String) VAR_S_R3.getValue(1));

			break;
		
		case STEP_4:
			
			s.Send(new AnBx_Params(s.sign(new AnBx_Params(aliases.get("ROLE_A"),s.getPublicKey(aliases.get("ROLE_A"),Crypto_KeyStoreType.pk()))),s.encrypt(s.sign(new AnBx_Params(VAR_S_DJ33SR3INVPS,KxKS,aliases.get("ROLE_B"),aliases.get("ROLE_A"))),aliases.get("ROLE_B"))));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}