/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:58:58.0434878 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package gsm;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class GSM_ROLE_M extends AnB_Protocol<GSM_Steps,GSM_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	
	// local vars
	private Crypto_ByteArray KiMH = null;
	private Crypto_ByteArray VAR_M_R1 = null;
	private Crypto_ByteArray VAR_M_KIMH = null;
	private SealedObject VAR_M_R3 = null;
	
	
	public GSM_ROLE_M(GSM_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         KiMH = (Crypto_ByteArray) AnB_Session.readObject(sharepath+"ki_"+aliases.get("ROLE_M")+"_"+aliases.get("ROLE_H")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		GSM_ROLE_M.sessions = sessions;
		
		AnB_Session ROLE_M_channel_ROLE_B_Server_Insecure = lbs.get("ROLE_M_channel_ROLE_B_Server_Insecure");
        
		init();
		
        ROLE_M_channel_ROLE_B_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_M_channel_ROLE_B_Server_Insecure, GSM_Steps.STEP_1);
					executeStep(ROLE_M_channel_ROLE_B_Server_Insecure, GSM_Steps.STEP_2);
					executeStep(ROLE_M_channel_ROLE_B_Server_Insecure, GSM_Steps.STEP_3);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_M_channel_ROLE_B_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, GSM_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_1:
			
			VAR_M_R1 = (Crypto_ByteArray) s.Receive();
			wffCheck("1.1",VAR_M_R1);

			break;
		
		case STEP_2:
			
			
			VAR_M_KIMH = KiMH;
			s.Send(s.makeDigest(new AnBx_Params(VAR_M_R1,VAR_M_KIMH)));

			break;
		
		case STEP_3:
			
			VAR_M_R3 = (SealedObject) s.Receive();
			wffCheck("3.1",(Crypto_ByteArray) s.decrypt(VAR_M_R3,kc(s,VAR_M_R1,VAR_M_KIMH)));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	private SecretKey kc(AnB_Session s,Crypto_ByteArray par1,Crypto_ByteArray par2) {
		return GSM_Functions.kc(s,par1,par2);
	}
	
	

	
	

}