/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:58:53.2735872 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package epmo;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class EPMO_ROLE_b extends AnB_Protocol<EPMO_Steps,EPMO_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray one = new Crypto_ByteArray("one".getBytes());
	private static Crypto_ByteArray two = new Crypto_ByteArray("two".getBytes());
	private static Crypto_ByteArray three = new Crypto_ByteArray("three".getBytes());
	private static Crypto_ByteArray four = new Crypto_ByteArray("four".getBytes());
	private static Crypto_ByteArray five = new Crypto_ByteArray("five".getBytes());
	private static Crypto_ByteArray six = new Crypto_ByteArray("six".getBytes());
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray NxB = null;
	private AnBx_Params VAR_B_R2 = null;
	private AnBx_Params VAR_B_DJ22BR2INVPB = null;
	private Crypto_ByteArray VAR_B_J34BDJ22BR2INVPB = null;
	private AnBx_Params VAR_B_R5 = null;
	
	
	public EPMO_ROLE_b(EPMO_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		EPMO_ROLE_b.sessions = sessions;
		
		AnB_Session ROLE_b_channel_ROLE_C_Server_Insecure = lbs.get("ROLE_b_channel_ROLE_C_Server_Insecure");
        AnB_Session ROLE_b_channel_ROLE_M_Server_Insecure = lbs.get("ROLE_b_channel_ROLE_M_Server_Insecure");
        
		init();
		
        ROLE_b_channel_ROLE_C_Server_Insecure.Open();
		ROLE_b_channel_ROLE_M_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_b_channel_ROLE_C_Server_Insecure, EPMO_Steps.STEP_2);
					executeStep(ROLE_b_channel_ROLE_C_Server_Insecure, EPMO_Steps.STEP_3);
					executeStep(ROLE_b_channel_ROLE_M_Server_Insecure, EPMO_Steps.STEP_5);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_b_channel_ROLE_C_Server_Insecure.Close();
		ROLE_b_channel_ROLE_M_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, EPMO_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_2:
			
			VAR_B_R2 = (AnBx_Params) s.Receive();
			VAR_B_DJ22BR2INVPB = (AnBx_Params) s.decrypt((Crypto_SealedPair) VAR_B_R2.getValue(1));
			eqCheck("2.1",aliases.get("ROLE_C"),(String) VAR_B_DJ22BR2INVPB.getValue(0));
			eqCheck("2.2",three,(Crypto_ByteArray) VAR_B_R2.getValue(0));

			break;
		
		case STEP_3:
			
			NxB = s.getNonce();
			VAR_B_J34BDJ22BR2INVPB = (Crypto_ByteArray) VAR_B_DJ22BR2INVPB.getValue(2);
			s.Send(new AnBx_Params(four,s.sign(s.makeDigest(new AnBx_Params(aliases.get("ROLE_C"),(Crypto_ByteArray) VAR_B_DJ22BR2INVPB.getValue(1),NxB,VAR_B_J34BDJ22BR2INVPB,(Crypto_ByteArray) VAR_B_DJ22BR2INVPB.getValue(3)))),s.encrypt(new AnBx_Params((Crypto_ByteArray) VAR_B_DJ22BR2INVPB.getValue(1),NxB),aliases.get("ROLE_C"))));

			break;
		
		case STEP_5:
			
			VAR_B_R5 = (AnBx_Params) s.Receive();
			eqCheck("5.1",six,(Crypto_ByteArray) VAR_B_R5.getValue(0));
			eqCheck("5.2",(Crypto_ByteArray) s.verify((SignedObject) VAR_B_R5.getValue(1),aliases.get("ROLE_M")),s.makeDigest(new AnBx_Params(aliases.get("ROLE_b"),NxB,VAR_B_J34BDJ22BR2INVPB)));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}