/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-08-27 19:10:26.7826963 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package sso_replay;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Random;

public final class SSO_replay_ROLE_SP extends AnB_Protocol<SSO_replay_Steps,SSO_replay_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray ID = null;
	private Crypto_ByteArray Data = null;
	private Crypto_SealedPair VAR_SP_R1 = null;
	private AnBx_Params VAR_SP_DDSPR1INVPSPSC = null;
	private String VAR_SP_J13SPDDSPR1INVPSPSC = null;
	private Crypto_ByteArray VAR_SP_J33SPDDSPR1INVPSPSC = null;
	private Crypto_SealedPair VAR_SP_R9 = null;
	private AnBx_Params VAR_SP_DDSPR9INVPSPSSPJ13SPDDSPR1INVPSPSC = null;
	private AnBx_Params VAR_SP_DJ12DDSPR9INVPSPSSPJ13SPDDSPR1INVPSPSCSIDP = null;
	private Crypto_ByteArray VAR_SP_J22SPDDSPR9INVPSPSSPJ13SPDDSPR1INVPSPSC = null;
	private AnBx_Params VAR_SP_DDSPR1INVPSPSSPJ13SPDDSPR1INVPSPSC = null;
	
	
	public SSO_replay_ROLE_SP(SSO_replay_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		SSO_replay_ROLE_SP.sessions = sessions;
		
		AnB_Session ROLE_SP_channel_ROLE_I_Server_Insecure = lbs.get("ROLE_SP_channel_ROLE_I_Server_Insecure");
        
		init();
		
        ROLE_SP_channel_ROLE_I_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_SP_channel_ROLE_I_Server_Insecure, SSO_replay_Steps.STEP_1);
					executeStep(ROLE_SP_channel_ROLE_I_Server_Insecure, SSO_replay_Steps.STEP_2);
					executeStep(ROLE_SP_channel_ROLE_I_Server_Insecure, SSO_replay_Steps.STEP_9);
					executeStep(ROLE_SP_channel_ROLE_I_Server_Insecure, SSO_replay_Steps.STEP_10);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_SP_channel_ROLE_I_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, SSO_replay_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_1:
			
			VAR_SP_R1 = (Crypto_SealedPair) s.Receive();
			VAR_SP_DDSPR1INVPSPSC = (AnBx_Params) s.verify((SignedObject) s.decrypt(VAR_SP_R1),aliases.get("ROLE_C"));
			eqCheck("1.1",aliases.get("ROLE_SP"),(String) VAR_SP_DDSPR1INVPSPSC.getValue(1));
			eqCheck("1.2",s.getPublicKey(aliases.get("ROLE_C"),Crypto_KeyStoreType.sk()),s.getPublicKey((String) VAR_SP_DDSPR1INVPSPSC.getValue(0),Crypto_KeyStoreType.sk()));

			break;
		
		case STEP_2:
			
			Data = s.getNonce();
			
			ID = s.getNonce();
			VAR_SP_J13SPDDSPR1INVPSPSC = (String) VAR_SP_DDSPR1INVPSPSC.getValue(0);
			VAR_SP_J33SPDDSPR1INVPSPSC = (Crypto_ByteArray) VAR_SP_DDSPR1INVPSPSC.getValue(2);
			s.Send(s.encrypt(s.sign(new AnBx_Params(VAR_SP_J13SPDDSPR1INVPSPSC,aliases.get("ROLE_idp"),aliases.get("ROLE_SP"),ID,VAR_SP_J33SPDDSPR1INVPSPSC)),s.getPublicKey(VAR_SP_J13SPDDSPR1INVPSPSC,Crypto_KeyStoreType.pk())));

			break;
		
		case STEP_9:
			
			VAR_SP_R9 = (Crypto_SealedPair) s.Receive();
			VAR_SP_DDSPR9INVPSPSSPJ13SPDDSPR1INVPSPSC = (AnBx_Params) s.verify((SignedObject) s.decrypt(VAR_SP_R9),s.getPublicKey(VAR_SP_J13SPDDSPR1INVPSPSC,Crypto_KeyStoreType.sk()));
			VAR_SP_DJ12DDSPR9INVPSPSSPJ13SPDDSPR1INVPSPSCSIDP = (AnBx_Params) s.verify((SignedObject) VAR_SP_DDSPR9INVPSPSSPJ13SPDDSPR1INVPSPSC.getValue(0),aliases.get("ROLE_idp"));
			wffCheck("9.1",(String) VAR_SP_DJ12DDSPR9INVPSPSSPJ13SPDDSPR1INVPSPSCSIDP.getValue(0));
			wffCheck("9.2",(SignedObject) VAR_SP_DDSPR9INVPSPSSPJ13SPDDSPR1INVPSPSC.getValue(0));
			VAR_SP_J22SPDDSPR9INVPSPSSPJ13SPDDSPR1INVPSPSC = (Crypto_ByteArray) VAR_SP_DDSPR9INVPSPSSPJ13SPDDSPR1INVPSPSC.getValue(1);
			wffCheck("9.3",VAR_SP_J22SPDDSPR9INVPSPSSPJ13SPDDSPR1INVPSPSC);
			VAR_SP_DDSPR1INVPSPSSPJ13SPDDSPR1INVPSPSC = (AnBx_Params) s.verify((SignedObject) s.decrypt(VAR_SP_R1),s.getPublicKey(VAR_SP_J13SPDDSPR1INVPSPSC,Crypto_KeyStoreType.sk()));
			eqCheck("9.4",aliases.get("ROLE_SP"),(String) VAR_SP_DDSPR1INVPSPSSPJ13SPDDSPR1INVPSPSC.getValue(1));
			eqCheck("9.5",VAR_SP_J33SPDDSPR1INVPSPSC,VAR_SP_J22SPDDSPR9INVPSPSSPJ13SPDDSPR1INVPSPSC);
			eqCheck("9.6",(Crypto_ByteArray) VAR_SP_DDSPR1INVPSPSSPJ13SPDDSPR1INVPSPSC.getValue(2),VAR_SP_J33SPDDSPR1INVPSPSC);
			eqCheck("9.7",VAR_SP_DJ12DDSPR9INVPSPSSPJ13SPDDSPR1INVPSPSCSIDP,new AnBx_Params(VAR_SP_J13SPDDSPR1INVPSPSC,aliases.get("ROLE_idp")));

			break;
		
		case STEP_10:
			
			s.Send(s.encrypt(s.sign(Data),s.getPublicKey(VAR_SP_J13SPDDSPR1INVPSPSC,Crypto_KeyStoreType.pk())));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}