/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-08-27 19:10:26.7826963 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package sso_replay;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Random;

public final class SSO_replay_ROLE_I extends AnB_Protocol<SSO_replay_Steps,SSO_replay_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_SealedPair VAR_I_R0 = null;
	private Crypto_SealedPair VAR_I_R2 = null;
	private Crypto_SealedPair VAR_I_R4 = null;
	private Crypto_SealedPair VAR_I_R6 = null;
	private Crypto_SealedPair VAR_I_R8 = null;
	private Crypto_SealedPair VAR_I_R10 = null;
	private Crypto_SealedPair VAR_I_REPLAY_R11 = null;
	
	
	public SSO_replay_ROLE_I(SSO_replay_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		SSO_replay_ROLE_I.sessions = sessions;
		
		AnB_Session ROLE_I_channel_ROLE_C_Server_Insecure = lbs.get("ROLE_I_channel_ROLE_C_Server_Insecure");
        AnB_Session ROLE_I_channel_ROLE_SP_Client_Insecure = lbs.get("ROLE_I_channel_ROLE_SP_Client_Insecure");
        AnB_Session ROLE_I_channel_ROLE_idp_Client_Insecure = lbs.get("ROLE_I_channel_ROLE_idp_Client_Insecure");
        
		init();
		
        ROLE_I_channel_ROLE_C_Server_Insecure.Open();
		ROLE_I_channel_ROLE_SP_Client_Insecure.Open();
		ROLE_I_channel_ROLE_idp_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_I_channel_ROLE_C_Server_Insecure, SSO_replay_Steps.STEP_0);
					executeStep(ROLE_I_channel_ROLE_SP_Client_Insecure, SSO_replay_Steps.STEP_1);
					executeStep(ROLE_I_channel_ROLE_SP_Client_Insecure, SSO_replay_Steps.STEP_2);
					executeStep(ROLE_I_channel_ROLE_C_Server_Insecure, SSO_replay_Steps.STEP_3);
					executeStep(ROLE_I_channel_ROLE_C_Server_Insecure, SSO_replay_Steps.STEP_4);
					executeStep(ROLE_I_channel_ROLE_idp_Client_Insecure, SSO_replay_Steps.STEP_5);
					executeStep(ROLE_I_channel_ROLE_idp_Client_Insecure, SSO_replay_Steps.STEP_6);
					executeStep(ROLE_I_channel_ROLE_C_Server_Insecure, SSO_replay_Steps.STEP_7);
					executeStep(ROLE_I_channel_ROLE_C_Server_Insecure, SSO_replay_Steps.STEP_8);
					executeStep(ROLE_I_channel_ROLE_SP_Client_Insecure, SSO_replay_Steps.STEP_9);
					executeStep(ROLE_I_channel_ROLE_SP_Client_Insecure, SSO_replay_Steps.STEP_10);
					executeStep(ROLE_I_channel_ROLE_C_Server_Insecure, SSO_replay_Steps.STEP_11);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_I_channel_ROLE_C_Server_Insecure.Close();
		ROLE_I_channel_ROLE_SP_Client_Insecure.Close();
		ROLE_I_channel_ROLE_idp_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, SSO_replay_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			VAR_I_R0 = (Crypto_SealedPair) s.Receive();
			wffCheck("0.1",VAR_I_R0);

			break;
		
		case STEP_1:
			
			s.Send(VAR_I_R0);

			break;
		
		case STEP_2:
			
			VAR_I_R2 = (Crypto_SealedPair) s.Receive();
			wffCheck("2.1",VAR_I_R2);

			break;
		
		case STEP_3:
			
			s.Send(VAR_I_R2);

			break;
		
		case STEP_4:
			
			VAR_I_R4 = (Crypto_SealedPair) s.Receive();
			wffCheck("4.1",VAR_I_R4);

			break;
		
		case STEP_5:
			
			s.Send(VAR_I_R4);

			break;
		
		case STEP_6:
			
			VAR_I_R6 = (Crypto_SealedPair) s.Receive();
			wffCheck("6.1",VAR_I_R6);

			break;
		
		case STEP_7:
			
			s.Send(VAR_I_R6);

			break;
		
		case STEP_8:
			
			VAR_I_R8 = (Crypto_SealedPair) s.Receive();
			wffCheck("8.1",VAR_I_R8);

			break;
		
		case STEP_9:
			
			s.Send(VAR_I_R8);

			break;
		
		case STEP_10:
			
			VAR_I_R10 = (Crypto_SealedPair) s.Receive();
			wffCheck("10.1",VAR_I_R10);

			break;
		
		case STEP_11:
			
			if (VAR_I_REPLAY_R11 == null || !(new Random().nextInt(10) < 5)) {
				AnBx_Debug.out(layer, ">>> NO ATTACK <<<");
				VAR_I_REPLAY_R11 = VAR_I_R10;
				s.Send(VAR_I_R10);
			} else {
				// Simulate attack by sending previous message
				AnBx_Debug.out(layer, ">>> ATTACK <<<");
				s.Send(VAR_I_REPLAY_R11);
			}

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}