/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:59:25.6660269 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package tls_pw;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class TLS_pw_ROLE_B extends AnB_Protocol<TLS_pw_Steps,TLS_pw_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private SecretKey PwAB = null;
	private Crypto_ByteArray NB = null;
	private Crypto_ByteArray PB = null;
	private SignedObject VAR_B_R0 = null;
	private AnBx_Params VAR_B_DBR0SS = null;
	private AnBx_Params VAR_B_R2 = null;
	private Crypto_ByteArray VAR_B_J34BR2 = null;
	private AnBx_Params VAR_B_R4 = null;
	private Crypto_ByteArray VAR_B_DJ13BR4INVPB = null;
	private Crypto_ByteArray VAR_B_HPRFBDJ13BR4INVPBJ24BR2NBABJ24BR2NBBJ34BR2J44BR2PBBDJ13BR4INVPB = null;
	
	
	public TLS_pw_ROLE_B(TLS_pw_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         PwAB = (SecretKey) AnB_Session.readObject(sharepath+"pw_"+aliases.get("ROLE_A")+"_"+aliases.get("ROLE_B")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		TLS_pw_ROLE_B.sessions = sessions;
		
		AnB_Session ROLE_B_channel_ROLE_s_Server_Secure = lbs.get("ROLE_B_channel_ROLE_s_Server_Secure");
        AnB_Session ROLE_B_channel_ROLE_A_Client_Insecure = lbs.get("ROLE_B_channel_ROLE_A_Client_Insecure");
        
		init();
		
        ROLE_B_channel_ROLE_s_Server_Secure.Open();
		ROLE_B_channel_ROLE_A_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_B_channel_ROLE_s_Server_Secure, TLS_pw_Steps.STEP_0);
					executeStep(ROLE_B_channel_ROLE_A_Client_Insecure, TLS_pw_Steps.STEP_1);
					executeStep(ROLE_B_channel_ROLE_A_Client_Insecure, TLS_pw_Steps.STEP_2);
					executeStep(ROLE_B_channel_ROLE_A_Client_Insecure, TLS_pw_Steps.STEP_3);
					executeStep(ROLE_B_channel_ROLE_A_Client_Insecure, TLS_pw_Steps.STEP_4);
					executeStep(ROLE_B_channel_ROLE_A_Client_Insecure, TLS_pw_Steps.STEP_5);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_B_channel_ROLE_s_Server_Secure.Close();
		ROLE_B_channel_ROLE_A_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, TLS_pw_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			VAR_B_R0 = (SignedObject) s.Receive();
			VAR_B_DBR0SS = (AnBx_Params) s.verify(VAR_B_R0,aliases.get("ROLE_s"));
			eqCheck("0.1",VAR_B_DBR0SS,new AnBx_Params(aliases.get("ROLE_B"),s.getPublicKey(aliases.get("ROLE_B"),Crypto_KeyStoreType.pk())));

			break;
		
		case STEP_1:
			
			s.Send(empty);

			break;
		
		case STEP_2:
			
			VAR_B_R2 = (AnBx_Params) s.Receive();
			eqCheck("2.1",aliases.get("ROLE_A"),(String) VAR_B_R2.getValue(0));

			break;
		
		case STEP_3:
			
			NB = s.getNonce();
			PB = s.getNonce();
			VAR_B_J34BR2 = (Crypto_ByteArray) VAR_B_R2.getValue(2);
			s.Send(new AnBx_Params(NB,VAR_B_J34BR2,PB,VAR_B_R0));

			break;
		
		case STEP_4:
			
			VAR_B_R4 = (AnBx_Params) s.Receive();
			VAR_B_DJ13BR4INVPB = (Crypto_ByteArray) s.decrypt((Crypto_SealedPair) VAR_B_R4.getValue(0));
			eqCheck("4.1",(Crypto_ByteArray) VAR_B_R4.getValue(1),s.makeDigest(new AnBx_Params(NB,aliases.get("ROLE_B"),VAR_B_DJ13BR4INVPB)));
			VAR_B_HPRFBDJ13BR4INVPBJ24BR2NBABJ24BR2NBBJ34BR2J44BR2PBBDJ13BR4INVPB = s.makeDigest(new AnBx_Params(prf(s,VAR_B_DJ13BR4INVPB,(Crypto_ByteArray) VAR_B_R2.getValue(1),NB),aliases.get("ROLE_A"),aliases.get("ROLE_B"),(Crypto_ByteArray) VAR_B_R2.getValue(1),NB,VAR_B_J34BR2,(Crypto_ByteArray) VAR_B_R2.getValue(3),PB,VAR_B_DJ13BR4INVPB));
			eqCheck("4.2",(Crypto_ByteArray) s.decrypt((SealedObject) VAR_B_R4.getValue(2),PwAB),VAR_B_HPRFBDJ13BR4INVPBJ24BR2NBABJ24BR2NBBJ34BR2J44BR2PBBDJ13BR4INVPB);

			break;
		
		case STEP_5:
			
			
			s.Send(s.encrypt(VAR_B_HPRFBDJ13BR4INVPBJ24BR2NBABJ24BR2NBBJ34BR2J44BR2PBBDJ13BR4INVPB,serverK(s,(Crypto_ByteArray) VAR_B_R2.getValue(1),NB,prf(s,VAR_B_DJ13BR4INVPB,(Crypto_ByteArray) VAR_B_R2.getValue(1),NB))));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	private SecretKey clientK(AnB_Session s,Crypto_ByteArray par1,Crypto_ByteArray par2,SecretKey par3) {
		return TLS_pw_Functions.clientK(s,par1,par2,par3);
	}
	
	private SecretKey serverK(AnB_Session s,Crypto_ByteArray par1,Crypto_ByteArray par2,SecretKey par3) {
		return TLS_pw_Functions.serverK(s,par1,par2,par3);
	}
	
	private SecretKey prf(AnB_Session s,Crypto_ByteArray par1,Crypto_ByteArray par2,Crypto_ByteArray par3) {
		return TLS_pw_Functions.prf(s,par1,par2,par3);
	}
	
	

	
	

}