/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:59:29.7562481 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package woolammutual;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class WooLamMutual_ROLE_A extends AnB_Protocol<WooLamMutual_Steps,WooLamMutual_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	
	// local vars
	private SecretKey ShkAs = null;
	private Crypto_ByteArray NA = null;
	private AnBx_Params VAR_A_R1 = null;
	private Crypto_ByteArray VAR_A_J22AR1 = null;
	private SecretKey VAR_A_SHKAS = null;
	private AnBx_Params VAR_A_R5 = null;
	private AnBx_Params VAR_A_DSJ12AR5ASHKAS = null;
	private AnBx_Params VAR_A_DSJ22AR5J44ADSJ12AR5ASHKAS = null;
	
	
	public WooLamMutual_ROLE_A(WooLamMutual_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         ShkAs = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_A")+"_"+aliases.get("ROLE_s")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		WooLamMutual_ROLE_A.sessions = sessions;
		
		AnB_Session ROLE_A_channel_ROLE_B_Client_Insecure = lbs.get("ROLE_A_channel_ROLE_B_Client_Insecure");
        
		init();
		
        ROLE_A_channel_ROLE_B_Client_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_A_channel_ROLE_B_Client_Insecure, WooLamMutual_Steps.STEP_0);
					executeStep(ROLE_A_channel_ROLE_B_Client_Insecure, WooLamMutual_Steps.STEP_1);
					executeStep(ROLE_A_channel_ROLE_B_Client_Insecure, WooLamMutual_Steps.STEP_2);
					executeStep(ROLE_A_channel_ROLE_B_Client_Insecure, WooLamMutual_Steps.STEP_5);
					executeStep(ROLE_A_channel_ROLE_B_Client_Insecure, WooLamMutual_Steps.STEP_6);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_A_channel_ROLE_B_Client_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, WooLamMutual_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			NA = s.getNonce();
			s.Send(new AnBx_Params(aliases.get("ROLE_A"),NA));

			break;
		
		case STEP_1:
			
			VAR_A_R1 = (AnBx_Params) s.Receive();
			eqCheck("1.1",aliases.get("ROLE_B"),(String) VAR_A_R1.getValue(0));

			break;
		
		case STEP_2:
			
			VAR_A_J22AR1 = (Crypto_ByteArray) VAR_A_R1.getValue(1);
			VAR_A_SHKAS = ShkAs;
			s.Send(s.encrypt(new AnBx_Params(aliases.get("ROLE_A"),aliases.get("ROLE_B"),NA,VAR_A_J22AR1),VAR_A_SHKAS));

			break;
		
		case STEP_5:
			
			VAR_A_R5 = (AnBx_Params) s.Receive();
			VAR_A_DSJ12AR5ASHKAS = (AnBx_Params) s.decrypt((SealedObject) VAR_A_R5.getValue(0),VAR_A_SHKAS);
			eqCheck("5.1",aliases.get("ROLE_B"),(String) VAR_A_DSJ12AR5ASHKAS.getValue(0));
			VAR_A_DSJ22AR5J44ADSJ12AR5ASHKAS = (AnBx_Params) s.decrypt((SealedObject) VAR_A_R5.getValue(1),(SecretKey) VAR_A_DSJ12AR5ASHKAS.getValue(3));
			eqCheck("5.2",NA,(Crypto_ByteArray) VAR_A_DSJ22AR5J44ADSJ12AR5ASHKAS.getValue(0));
			eqCheck("5.3",NA,(Crypto_ByteArray) VAR_A_DSJ12AR5ASHKAS.getValue(1));
			eqCheck("5.4",VAR_A_J22AR1,(Crypto_ByteArray) VAR_A_DSJ22AR5J44ADSJ12AR5ASHKAS.getValue(1));
			eqCheck("5.5",VAR_A_J22AR1,(Crypto_ByteArray) VAR_A_DSJ12AR5ASHKAS.getValue(2));

			break;
		
		case STEP_6:
			
			s.Send(s.encrypt(VAR_A_J22AR1,(SecretKey) VAR_A_DSJ12AR5ASHKAS.getValue(3)));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}