/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:58:58.7377552 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package h530fix;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class H530fix_ROLE_s extends AnB_Protocol<H530fix_Steps,H530fix_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray t1 = new Crypto_ByteArray("t1".getBytes());
	private static Crypto_ByteArray t2 = new Crypto_ByteArray("t2".getBytes());
	private static Crypto_ByteArray t3 = new Crypto_ByteArray("t3".getBytes());
	private static Crypto_ByteArray t4 = new Crypto_ByteArray("t4".getBytes());
	private static Crypto_ByteArray t5 = new Crypto_ByteArray("t5".getBytes());
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private SecretKey ShkAs = null;
	private SecretKey ShkBs = null;
	private AnBx_Params VAR_S_R1 = null;
	private PublicKey VAR_S_J38SR1 = null;
	private Crypto_ByteArray VAR_S_J48SR1 = null;
	private SecretKey VAR_S_SHKAS = null;
	private PublicKey VAR_S_J68SR1 = null;
	private PublicKey VAR_S_J78SR1 = null;
	private SecretKey VAR_S_SHKBS = null;
	private Crypto_ByteArray VAR_S_HSSHKAST3BSJ68SR1SJ78SR1 = null;
	
	
	public H530fix_ROLE_s(H530fix_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         ShkAs = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_A")+"_"+aliases.get("ROLE_s")+".ser");
		 ShkBs = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_B")+"_"+aliases.get("ROLE_s")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		H530fix_ROLE_s.sessions = sessions;
		
		AnB_Session ROLE_s_channel_ROLE_B_Server_Insecure = lbs.get("ROLE_s_channel_ROLE_B_Server_Insecure");
        
		init();
		
        ROLE_s_channel_ROLE_B_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_s_channel_ROLE_B_Server_Insecure, H530fix_Steps.STEP_1);
					executeStep(ROLE_s_channel_ROLE_B_Server_Insecure, H530fix_Steps.STEP_2);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_s_channel_ROLE_B_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, H530fix_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_1:
			
			VAR_S_R1 = (AnBx_Params) s.Receive();
			eqCheck("1.1",aliases.get("ROLE_A"),(String) VAR_S_R1.getValue(0));
			eqCheck("1.2",aliases.get("ROLE_B"),(String) VAR_S_R1.getValue(1));
			eqCheck("1.3",aliases.get("ROLE_B"),(String) VAR_S_R1.getValue(4));
			VAR_S_J38SR1 = (PublicKey) VAR_S_R1.getValue(2);
			VAR_S_J48SR1 = (Crypto_ByteArray) VAR_S_R1.getValue(3);
			VAR_S_SHKAS = ShkAs;
			eqCheck("1.4",VAR_S_J48SR1,s.makeDigest(new AnBx_Params(VAR_S_SHKAS,t1,aliases.get("ROLE_A"),aliases.get("ROLE_B"),VAR_S_J38SR1)));
			VAR_S_J68SR1 = (PublicKey) VAR_S_R1.getValue(5);
			eqCheck("1.5",VAR_S_J68SR1,VAR_S_J38SR1);
			VAR_S_J78SR1 = (PublicKey) VAR_S_R1.getValue(6);
			VAR_S_SHKBS = ShkBs;
			eqCheck("1.6",(Crypto_ByteArray) VAR_S_R1.getValue(7),s.makeDigest(new AnBx_Params(VAR_S_SHKBS,t2,aliases.get("ROLE_A"),aliases.get("ROLE_B"),VAR_S_J68SR1,VAR_S_J48SR1,aliases.get("ROLE_B"),VAR_S_J68SR1,VAR_S_J78SR1)));

			break;
		
		case STEP_2:
			
			VAR_S_HSSHKAST3BSJ68SR1SJ78SR1 = s.makeDigest(new AnBx_Params(VAR_S_SHKAS,t3,aliases.get("ROLE_B"),VAR_S_J68SR1,VAR_S_J78SR1));
			s.Send(new AnBx_Params(aliases.get("ROLE_B"),aliases.get("ROLE_A"),VAR_S_J68SR1,VAR_S_HSSHKAST3BSJ68SR1SJ78SR1,s.makeDigest(new AnBx_Params(VAR_S_SHKBS,t4,aliases.get("ROLE_B"),aliases.get("ROLE_A"),VAR_S_J68SR1,VAR_S_HSSHKAST3BSJ68SR1SJ78SR1))));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}