/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:58:59.0833929 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package ikev2ds;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class IKEv2DS_ROLE_B extends AnB_Protocol<IKEv2DS_Steps,IKEv2DS_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	
	// local vars
	private Crypto_ByteArray Nb = null;
	private KeyPair YxKEb = null;
	private AnBx_Params VAR_B_R0 = null;
	private Crypto_ByteArray VAR_B_J35BR0 = null;
	private SealedObject VAR_B_R2 = null;
	private AnBx_Params VAR_B_DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB = null;
	private AnBx_Params VAR_B_DJ23DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ13DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB = null;
	private Crypto_ByteArray VAR_B_J14BDJ23DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ13DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB = null;
	private PublicKey VAR_B_J45BR0 = null;
	private Crypto_ByteArray VAR_B_J55BR0 = null;
	private SealedObject VAR_B_R4 = null;
	private AnBx_Params VAR_B_DJ23BDSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ15BR0 = null;
	
	
	public IKEv2DS_ROLE_B(IKEv2DS_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		IKEv2DS_ROLE_B.sessions = sessions;
		
		AnB_Session ROLE_B_channel_ROLE_A_Server_Insecure = lbs.get("ROLE_B_channel_ROLE_A_Server_Insecure");
        
		init();
		
        ROLE_B_channel_ROLE_A_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, IKEv2DS_Steps.STEP_0);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, IKEv2DS_Steps.STEP_1);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, IKEv2DS_Steps.STEP_2);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, IKEv2DS_Steps.STEP_3);
					executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, IKEv2DS_Steps.STEP_4);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_B_channel_ROLE_A_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, IKEv2DS_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_0:
			
			noteqCheck("0.2",aliases.get("ROLE_B"),aliases.get("ROLE_A"));
			VAR_B_R0 = (AnBx_Params) s.Receive();
			eqCheck("0.1",aliases.get("ROLE_B"),(String) VAR_B_R0.getValue(1));

			break;
		
		case STEP_1:
			
			YxKEb = s.getKeyEx_KeyPair();
			
			Nb = s.getNonce();
			VAR_B_J35BR0 = (Crypto_ByteArray) VAR_B_R0.getValue(2);
			s.Send(new AnBx_Params(VAR_B_J35BR0,s.getKeyEx_PublicKey(YxKEb),Nb));

			break;
		
		case STEP_2:
			
			VAR_B_R2 = (SealedObject) s.Receive();
			VAR_B_DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB = (AnBx_Params) s.decrypt(VAR_B_R2,h(s,(Crypto_ByteArray) VAR_B_R0.getValue(4),Nb,VAR_B_J35BR0,s.getKeyEx_SecretKey((PublicKey) VAR_B_R0.getValue(3),YxKEb)));
			VAR_B_DJ23DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ13DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB = (AnBx_Params) s.verify((SignedObject) VAR_B_DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB.getValue(1),s.getPublicKey((String) VAR_B_DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB.getValue(0),Crypto_KeyStoreType.sk()));
			eqCheck("2.1",Nb,(Crypto_ByteArray) VAR_B_DJ23DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ13DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB.getValue(3));
			eqCheck("2.2",(String) VAR_B_R0.getValue(0),(String) VAR_B_DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB.getValue(0));
			VAR_B_J14BDJ23DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ13DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB = (Crypto_ByteArray) VAR_B_DJ23DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ13DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB.getValue(0);
			eqCheck("2.3",(Crypto_ByteArray) VAR_B_DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB.getValue(2),VAR_B_J14BDJ23DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ13DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB);
			eqCheck("2.4",VAR_B_J35BR0,VAR_B_J14BDJ23DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ13DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB);
			VAR_B_J45BR0 = (PublicKey) VAR_B_R0.getValue(3);
			eqCheck("2.5",VAR_B_J45BR0,(PublicKey) VAR_B_DJ23DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ13DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB.getValue(1));
			VAR_B_J55BR0 = (Crypto_ByteArray) VAR_B_R0.getValue(4);
			eqCheck("2.6",VAR_B_J55BR0,(Crypto_ByteArray) VAR_B_DJ23DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ13DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB.getValue(2));

			break;
		
		case STEP_3:
			
			s.Send(s.encrypt(new AnBx_Params(aliases.get("ROLE_B"),s.sign(new AnBx_Params(VAR_B_J35BR0,s.getKeyEx_PublicKey(YxKEb),VAR_B_J55BR0,Nb)),VAR_B_J35BR0),h(s,VAR_B_J55BR0,Nb,VAR_B_J35BR0,s.getKeyEx_SecretKey(VAR_B_J45BR0,YxKEb))));

			break;
		
		case STEP_4:
			
			VAR_B_R4 = (SealedObject) s.Receive();
			wffCheck("4.1",(Crypto_ByteArray) s.decrypt(VAR_B_R4,s.getKeyEx_SecretKey(VAR_B_J45BR0,YxKEb)));
			VAR_B_DJ23BDSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ15BR0 = (AnBx_Params) s.verify((SignedObject) VAR_B_DSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEB.getValue(1),s.getPublicKey((String) VAR_B_R0.getValue(0),Crypto_KeyStoreType.sk()));
			eqCheck("4.2",Nb,(Crypto_ByteArray) VAR_B_DJ23BDSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ15BR0.getValue(3));
			eqCheck("4.3",VAR_B_J35BR0,(Crypto_ByteArray) VAR_B_DJ23BDSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ15BR0.getValue(0));
			eqCheck("4.4",VAR_B_J45BR0,(PublicKey) VAR_B_DJ23BDSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ15BR0.getValue(1));
			eqCheck("4.5",VAR_B_J55BR0,(Crypto_ByteArray) VAR_B_DJ23BDSBR2HJ55BR0NBBJ35BR0KASJ45BR0YXKEBSJ15BR0.getValue(2));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	private SecretKey h(AnB_Session s,Crypto_ByteArray par1,Crypto_ByteArray par2,Crypto_ByteArray par3,SecretKey par4) {
		return IKEv2DS_Functions.h(s,par1,par2,par3,par4);
	}
	
	

	
	

}