/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.01 on 2025-02-04 11:59:05.5318374 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package kerberos_pkinit;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;

public final class Kerberos_PKINIT_ROLE_s extends AnB_Protocol<Kerberos_PKINIT_Steps,Kerberos_PKINIT_Roles> {

//	private static boolean loop = false;
	private static long sessionID = 0;

	// local knowledge - constants
	private static Crypto_ByteArray tag = new Crypto_ByteArray("tag".getBytes());
	
	// local vars
	private SecretKey ShkGws = null;
	private Crypto_ByteArray Payload = null;
	private AnBx_Params VAR_S_R4 = null;
	private AnBx_Params VAR_S_DSJ12SR4SHKGWS = null;
	private AnBx_Params VAR_S_DSJ22SR4J34SDSJ12SR4SHKGWS = null;
	private Crypto_ByteArray VAR_S_HJ44SDSJ12SR4SHKGWS = null;
	
	
	public Kerberos_PKINIT_ROLE_s(Kerberos_PKINIT_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
		if (sessionID < Long.MAX_VALUE) {
			sessionID++;
		}
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         ShkGws = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_gw")+"_"+aliases.get("ROLE_s")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {

		this.aliases = aliases;
		this.lbs = lbs;
		Kerberos_PKINIT_ROLE_s.sessions = sessions;
		
		AnB_Session ROLE_s_channel_ROLE_C_Server_Insecure = lbs.get("ROLE_s_channel_ROLE_C_Server_Insecure");
        
		init();
		
        ROLE_s_channel_ROLE_C_Server_Insecure.Open();
		  
		do {
			AnBx_Debug.out(layer, "Session started: " + sessionID + "/" + sessions);

			try {

                    executeStep(ROLE_s_channel_ROLE_C_Server_Insecure, Kerberos_PKINIT_Steps.STEP_4);
					executeStep(ROLE_s_channel_ROLE_C_Server_Insecure, Kerberos_PKINIT_Steps.STEP_5);
					
                    AnBx_Debug.out(layer, "Session completed: " + sessionID + "/" + sessions);
                    sessionID++;
			
			} catch (ClassCastException e) {
				abort("Message format type error",e,sessionID);
			} catch (NullPointerException e) {
				abort("Some data have not been properly initialised",e,sessionID);
			} catch (Exception e) {
				abort("Generic error",e,sessionID);
			}
		} while ((sessionID <= sessions && sessionID < Long.MAX_VALUE) || sessions < 0);
        ROLE_s_channel_ROLE_C_Server_Insecure.Close();
		
	};

	protected void executeStep(AnB_Session s, Kerberos_PKINIT_Steps step) {

		status(step);

		switch (step) {
		
		case STEP_4:
			
			VAR_S_R4 = (AnBx_Params) s.Receive();
			VAR_S_DSJ12SR4SHKGWS = (AnBx_Params) s.decrypt((SealedObject) VAR_S_R4.getValue(0),ShkGws);
			eqCheck("4.1",aliases.get("ROLE_s"),(String) VAR_S_DSJ12SR4SHKGWS.getValue(1));
			VAR_S_DSJ22SR4J34SDSJ12SR4SHKGWS = (AnBx_Params) s.decrypt((SealedObject) VAR_S_R4.getValue(1),(SecretKey) VAR_S_DSJ12SR4SHKGWS.getValue(2));
			eqCheck("4.2",(String) VAR_S_DSJ12SR4SHKGWS.getValue(0),(String) VAR_S_DSJ22SR4J34SDSJ12SR4SHKGWS.getValue(0));
			VAR_S_HJ44SDSJ12SR4SHKGWS = s.makeDigest((Crypto_ByteArray) VAR_S_DSJ12SR4SHKGWS.getValue(3));
			eqCheck("4.3",VAR_S_HJ44SDSJ12SR4SHKGWS,(Crypto_ByteArray) VAR_S_DSJ22SR4J34SDSJ12SR4SHKGWS.getValue(1));

			break;
		
		case STEP_5:
			
			Payload = s.getNonce();
			
			s.Send(new AnBx_Params(s.encrypt(VAR_S_HJ44SDSJ12SR4SHKGWS,(SecretKey) VAR_S_DSJ12SR4SHKGWS.getValue(2)),s.encrypt(new AnBx_Params(tag,Payload),(SecretKey) VAR_S_DSJ12SR4SHKGWS.getValue(2))));

			break;
		
		default:
			
            break;		
		}

		status(step);

	}

	

	
	

}