/*

 AnBx Compiler and Code Generator

 Copyright 2011-2024 Paolo Modesti
 Copyright 2018-2024 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2024.08 on 2025-07-07 11:18:51.412797 UTC

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/
package isosk2pmap;

import anbxj.AnBx_Layers;
import anbxj.AnB_Crypto_Wrapper;

public class ISOSK2PMAP {

	final static AnBx_Layers layer = AnBx_Layers.APPLICATION;

	public static void main(String[] args) {

		AnB_Crypto_Wrapper.setLoggingExecTimeEnabled(false);
        long start = System.nanoTime();

		ISOSK2PMAP_CommandLine_Parser p = new ISOSK2PMAP_CommandLine_Parser(args,ISOSK2PMAP.class.getSimpleName());

        long end = System.nanoTime();
      	double durationInMs = (end - start) / 1_000_000.0;
		System.out.println(String.format("%s - Execution time was %.3f ms.", "ISOSK2PMAP [" + p.getRole() + "]", durationInMs));


	}
}